<a href="https://colab.research.google.com/github/etmcrae/Who-Got-DOGEd-/blob/main/DOGE_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


```
** Department of Government Efficiency (DOGE) API ** **bold text**
```

**Contains Savings & Payments**

Savings include: grants, contracts, leases

Payments include: payments, statistics

Source is https://doge.gov/savings

**From https://github.com/m-nolan/doge-scrape/blob/main/doge-scrape.py**

might need to update the USAspending data from https://api.usaspending.gov/docs/endpoints

In [ ]:
import os
from datetime import datetime
from time import sleep

import numpy as np
import pandas as pd
import requests as req
!pip install validators
!pip install ratelimit # Install the ratelimit package
from bs4 import BeautifulSoup
from ratelimit import limits, sleep_and_retry
!pip install selenium
from selenium.webdriver import Firefox
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from tqdm import tqdm

Requirement already satisfied: validators in /usr/local/lib/python3.11/dist-packages (0.35.0)
Requirement already satisfied: ratelimit in /usr/local/lib/python3.11/dist-packages (2.2.1)
Requirement already satisfied: selenium in /usr/local/lib/python3.11/dist-packages (4.33.0)
Requirement already satisfied: urllib3~=2.4.0 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (2.4.0)
Requirement already satisfied: trio~=0.30.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.4.26 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.4.26)
Requirement already satisfied: typing_extensions~=4.13.2 in /usr/local/lib/python3.11/dist-packages (from selenium) (4.13.2)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (3.10)
Requirement already satisfied: outcome in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.11/dist-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)

In [ ]:
!wget https://files.usaspending.gov/award_data_archive/FY2025_All_Contracts_Full_20250506.zip
!unzip FY2025_All_Contracts_Full_20250506.zip

--2025-06-06 19:24:50--  https://files.usaspending.gov/award_data_archive/FY2025_All_Contracts_Full_20250506.zip
Resolving files.usaspending.gov (files.usaspending.gov)... 166.123.8.118, 2610:108:4100:100c::9:168
Connecting to files.usaspending.gov (files.usaspending.gov)|166.123.8.118|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 739753150 (705M) [application/zip]
Saving to: ‘FY2025_All_Contracts_Full_20250506.zip’

FY2025_All_Contract 100%[===================>] 705.48M  48.6MB/s    in 18s

2025-06-06 19:25:09 (39.1 MB/s) - ‘FY2025_All_Contracts_Full_20250506.zip’ saved [739753150/739753150]

Archive:  FY2025_All_Contracts_Full_20250506.zip
  inflating: FY2025_All_Contracts_Full_20250508_1.csv
  inflating: FY2025_All_Contracts_Full_20250508_2.csv
  inflating: FY2025_All_Contracts_Full_20250508_3.csv

In [ ]:
!ls -la

total 5916284
drwxr-xr-x 1 root root       4096 Jun  6 19:25 .
drwxr-xr-x 1 root root       4096 Jun  6 19:23 ..
drwxr-xr-x 4 root root       4096 Jun  5 13:38 .config
-rw-r--r-- 1 root root  739753150 May 13 19:08 FY2025_All_Contracts_Full_20250506.zip
-rw-r--r-- 1 root root 2179860288 May  9 01:52 FY2025_All_Contracts_Full_20250508_1.csv
-rw-r--r-- 1 root root 2099189096 May  9 01:53 FY2025_All_Contracts_Full_20250508_2.csv
-rw-r--r-- 1 root root 1039433226 May  9 01:54 FY2025_All_Contracts_Full_20250508_3.csv
drwxr-xr-x 1 root root       4096 Jun  5 13:38 sample_data

In [ ]:
!unzip -l ../FY2025_All_Contracts_Full_20250506.zip
!unzip ../FY2025_All_Contracts_Full_20250506.zip

unzip:  cannot find or open ../FY2025_All_Contracts_Full_20250506.zip, ../FY2025_All_Contracts_Full_20250506.zip.zip or ../FY2025_All_Contracts_Full_20250506.zip.ZIP.
unzip:  cannot find or open ../FY2025_All_Contracts_Full_20250506.zip, ../FY2025_All_Contracts_Full_20250506.zip.zip or ../FY2025_All_Contracts_Full_20250506.zip.ZIP.
total 5916284
drwxr-xr-x 1 root root       4096 Jun  6 19:25 .
drwxr-xr-x 1 root root       4096 Jun  6 19:23 ..
drwxr-xr-x 4 root root       4096 Jun  5 13:38 .config
-rw-r--r-- 1 root root  739753150 May 13 19:08 FY2025_All_Contracts_Full_20250506.zip
-rw-r--r-- 1 root root 2179860288 May  9 01:52 FY2025_All_Contracts_Full_20250508_1.csv
-rw-r--r-- 1 root root 2099189096 May  9 01:53 FY2025_All_Contracts_Full_20250508_2.csv
-rw-r--r-- 1 root root 1039433226 May  9 01:54 FY2025_All_Contracts_Full_20250508_3.csv
drwxr-xr-x 1 root root       4096 Jun  5 13:38 sample_data

<ipython-input-7-5cbc6ca64e50>:4: DtypeWarning: Columns (5,47,68,71,72,81,107,108,115,116,117,118,135,136,164,165,171,172,179,180) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv')

In [ ]:
!ls -la

total 5916284
drwxr-xr-x 1 root root       4096 Jun  6 19:25 .
drwxr-xr-x 1 root root       4096 Jun  6 19:23 ..
drwxr-xr-x 4 root root       4096 Jun  5 13:38 .config
-rw-r--r-- 1 root root  739753150 May 13 19:08 FY2025_All_Contracts_Full_20250506.zip
-rw-r--r-- 1 root root 2179860288 May  9 01:52 FY2025_All_Contracts_Full_20250508_1.csv
-rw-r--r-- 1 root root 2099189096 May  9 01:53 FY2025_All_Contracts_Full_20250508_2.csv
-rw-r--r-- 1 root root 1039433226 May  9 01:54 FY2025_All_Contracts_Full_20250508_3.csv
drwxr-xr-x 1 root root       4096 Jun  5 13:38 sample_data

In [ ]:
!wc FY2025_All_Contracts_Full_20250508_*

   1000001  123129882 2179860288 FY2025_All_Contracts_Full_20250508_1.csv
   1000001  113663795 2099189096 FY2025_All_Contracts_Full_20250508_2.csv
    500727   55654447 1039433226 FY2025_All_Contracts_Full_20250508_3.csv
   2500729  292448124 5318482610 total

In [ ]:
df0 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv', nrows=3)

In [ ]:
cols3 = list(df0.columns)

In [ ]:
len(cols3), len(cols2), len(cols1)

(297, 297, 297)

In [ ]:
cols1==cols2==cols3

True

In [ ]:
df1 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', nrows=100)

In [ ]:
# keep = [
    2,
    10,
    15,
    23,
    26,
    29,
    31,
    35,
    37,
    44,
    50,
    53,
    59,
    60,
    62,
    64,
    65,
    66,
    67,
    68.
    71,
    109,
    110,
    144,
    159,
    161,
    163,
    176,
    187,
    186,
    187,
    194,
    195:296
   ]

keep

In [ ]:
df1.describe(include='all').transpose().reset_index()

,index,count,unique,top,freq,mean,std,min,25%,50%,75%,max
0,contract_transaction_unique_key,100,100,4732_-NONE-_47QSWA20D0092_PA0042_-NONE-_-NONE-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,contract_award_unique_key,100,100,CONT_IDV_47QSWA20D0092_4732,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,award_id_piid,100,100,47QSWA20D0092,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,modification_number,100,17,PSA897,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,transaction_number,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,parent_award_agency_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,parent_award_agency_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,parent_award_id_piid,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,parent_award_modification_number,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,federal_action_obligation,100.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,total_dollars_obligated,100.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,total_outlayed_amount_for_overall_award,2.0,NaN,NaN,NaN,353236.24,479262.211899,14346.68,183791.46,353236.24,522681.02,692125.8
12,base_and_exercised_options_value,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,current_total_value_of_award,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,base_and_all_options_value,100.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,potential_total_value_of_award,100.0,NaN,NaN,NaN,10723995.75,41160585.434537,100000.0,500000.0,1137782.5,6835165.0,400000000.0
16,disaster_emergency_fund_codes_for_overall_award,2,1,Q: Not Designated Nonemergency/Emergency/Disas...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,outlayed_amount_from_COVID-19_supplementals_fo...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,obligated_amount_from_COVID-19_supplementals_f...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,outlayed_amount_from_IIJA_supplemental_for_ove...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,obligated_amount_from_IIJA_supplemental_for_ov...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,action_date,100,1,2025-05-03,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,action_date_fiscal_year,100.0,NaN,NaN,NaN,2025.0,0.0,2025.0,2025.0,2025.0,2025.0,2025.0
23,period_of_performance_start_date,100,98,2024-09-05,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,period_of_performance_current_end_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,period_of_performance_potential_end_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,ordering_period_end_date,100,97,2028-03-31,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,solicitation_date,57,24,2020-11-09,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,awarding_agency_code,100.0,NaN,NaN,NaN,46.72,2.8,19.0,47.0,47.0,47.0,47.0
29,awarding_agency_name,100,2,General Services Administration,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,awarding_sub_agency_code,100.0,NaN,NaN,NaN,4703.68,283.2,1900.0,4732.0,4732.0,4732.0,4732.0
31,awarding_sub_agency_name,100,2,Federal Acquisition Service,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,awarding_office_code,100,5,47QRAA,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,awarding_office_name,100,5,GSA/FAS/PSHC/PROF SRVCS SCHED-PSS,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,funding_agency_code,100.0,NaN,NaN,NaN,46.72,2.8,19.0,47.0,47.0,47.0,47.0
35,funding_agency_name,100,2,General Services Administration,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,funding_sub_agency_code,100.0,NaN,NaN,NaN,4703.68,283.2,1900.0,4732.0,4732.0,4732.0,4732.0
37,funding_sub_agency_name,100,2,Federal Acquisition Service,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,funding_office_code,100,5,47QRAA,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,funding_office_name,100,5,GSA/FAS/PSHC/PROF SRVCS SCHED-PSS,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,treasury_accounts_funding_this_award,4,2,047-X-4534-001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,federal_accounts_funding_this_award,4,2,047-4534,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,object_classes_funding_this_award,4,3,26.0: Supplies and materials,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,program_activities_funding_this_award,4,2,0852: GENERAL SUPPLIES AND SERVICES (GSS) - FL...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,foreign_funding,100,1,X,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,foreign_funding_description,100,1,NOT APPLICABLE,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,sam_exception,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,sam_exception_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,recipient_uei,100,99,YY2KG4HQL8K4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,recipient_duns,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,recipient_name,100,99,AUCTOR CORPORATION,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,recipient_name_raw,100,99,AUCTOR CORPORATION,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,recipient_doing_business_as_name,13,13,EVENT HYDRATION SOLUTIONS INC,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,cage_code,100,99,4ALR4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,recipient_parent_uei,100,99,YY2KG4HQL8K4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,recipient_parent_duns,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,recipient_parent_name,100,99,AUCTOR CORPORATION,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,recipient_parent_name_raw,100,99,AUCTOR CORPORATION,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,recipient_country_code,100,2,USA,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,recipient_country_name,100,2,UNITED STATES,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,recipient_address_line_1,100,99,9449 PRIORITY WAY WEST DR STE 150,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,recipient_address_line_2,21,19,STE 300,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,recipient_city_name,100,82,ARLINGTON,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,prime_award_transaction_recipient_county_fips_...,99.0,NaN,NaN,NaN,31786.585859,18642.16266,1089.0,12109.0,34009.0,51059.0,72127.0
64,recipient_county_name,99,61,FAIRFAX,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,prime_award_transaction_recipient_state_fips_code,99.0,NaN,NaN,NaN,31.69697,18.614486,1.0,12.0,34.0,51.0,72.0
66,recipient_state_code,99,31,VA,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,recipient_state_name,100,32,VIRGINIA,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,recipient_zip_4_code,100,99,462406421,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,prime_award_transaction_recipient_cd_original,99,64,VA-11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,prime_award_transaction_recipient_cd_current,99,63,VA-11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,recipient_phone_number,99.0,NaN,NaN,NaN,5615053998.393939,2298507844.593847,2022075155.0,3203365964.0,6097051229.0,7039621765.5,9739029266.0
72,recipient_fax_number,57.0,NaN,NaN,NaN,5681963211.368421,2383009586.977569,2025998439.0,3175697481.0,6788681235.0,7187490113.0,9734473300.0
73,primary_place_of_performance_country_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,primary_place_of_performance_country_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,primary_place_of_performance_city_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,prime_award_transaction_place_of_performance_c...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,primary_place_of_performance_county_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,prime_award_transaction_place_of_performance_s...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,primary_place_of_performance_state_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,primary_place_of_performance_state_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,primary_place_of_performance_zip_4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,prime_award_transaction_place_of_performance_c...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,prime_award_transaction_place_of_performance_c...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,award_or_idv_flag,100,1,IDV,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,award_type_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,award_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,idv_type_code,100,2,C,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,idv_type,100,2,FSS,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,multiple_or_single_award_idv_code,100,1,M,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,multiple_or_single_award_idv,100,1,MULTIPLE AWARD,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,type_of_idc_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,type_of_idc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,type_of_contract_pricing_code,100,2,K,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,type_of_contract_pricing,100,2,FIXED PRICE WITH ECONOMIC PRICE ADJUSTMENT,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,transaction_description,100,2,FEDERAL SUPPLY SCHEDULE CONTRACT,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,prime_award_base_transaction_description,100,5,FEDERAL SUPPLY SCHEDULE CONTRACT,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,action_type_code,100,1,M,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,action_type,100,1,OTHER ADMINISTRATIVE ACTION,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,solicitation_identifier,91,13,47QSMD20R0001,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,number_of_actions,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,inherently_governmental_functions,1,1,OT,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,inherently_governmental_functions_description,1,1,OTHER FUNCTIONS,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,product_or_service_code,100,33,D399,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,product_or_service_code_description,100,33,IT AND TELECOM- OTHER IT AND TELECOMMUNICATIONS,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,contract_bundling_code,100,2,H,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,contract_bundling,100,2,NOT BUNDLED,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,dod_claimant_program_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,dod_claimant_program_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,naics_code,100.0,NaN,NaN,NaN,521659.02,75321.586995,311423.0,541330.0,541511.0,541611.0,811212.0
110,naics_description,100,40,CUSTOM COMPUTER PROGRAMMING SERVICES,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,recovered_materials_sustainability_code,26,1,A,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,recovered_materials_sustainability,26,1,FAR 52.223-4 INCLUDED,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,domestic_or_foreign_entity_code,94,3,A,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,domestic_or_foreign_entity,94,3,U.S. OWNED BUSINESS,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,dod_acquisition_program_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,dod_acquisition_program_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,information_technology_commercial_item_categor...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,information_technology_commercial_item_category,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,epa_designated_product_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,epa_designated_product,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,country_of_product_or_service_origin_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,country_of_product_or_service_origin,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,place_of_manufacture_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,place_of_manufacture,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,subcontracting_plan_code,99,4,B,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,subcontracting_plan,99,4,PLAN NOT REQUIRED,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,extent_competed_code,99,2,A,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,extent_competed,99,2,FULL AND OPEN COMPETITION,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,solicitation_procedures_code,99,1,NP,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,solicitation_procedures,99,1,NEGOTIATED PROPOSAL/QUOTE,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,type_of_set_aside_code,99,2,NONE,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,type_of_set_aside,99,2,NO SET ASIDE USED.,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,evaluated_preference_code,99,1,NONE,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,evaluated_preference,99,1,NO PREFERENCE USED,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,research_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,research,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,fair_opportunity_limited_sources_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,fair_opportunity_limited_sources,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,other_than_full_and_open_competition_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,other_than_full_and_open_competition,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,number_of_offers_received,99.0,NaN,NaN,NaN,999.0,0.0,999.0,999.0,999.0,999.0,999.0
142,commercial_item_acquisition_procedures_code,100,2,A,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,commercial_item_acquisition_procedures,100,2,COMMERCIAL PRODUCTS/SERVICES,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,small_business_competitiveness_demonstration_p...,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,simplified_procedures_for_certain_commercial_i...,99,1,N,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,simplified_procedures_for_certain_commercial_i...,99,1,NO,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,a76_fair_act_action_code,72,1,N,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,a76_fair_act_action,72,1,NO,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,fed_biz_opps_code,100,2,Y,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,fed_biz_opps,100,2,YES,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,local_area_set_aside_code,92,1,N,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,local_area_set_aside,92,1,NO,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,price_evaluation_adjustment_preference_percent...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,clinger_cohen_act_planning_code,100,2,N,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,clinger_cohen_act_planning,100,2,NO,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,materials_supplies_articles_equipment_code,100,2,X,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,materials_supplies_articles_equipment,100,2,NOT APPLICABLE,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,labor_standards_code,100,3,Y,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,labor_standards,100,3,YES,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,construction_wage_rate_requirements_code,100,2,X,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,construction_wage_rate_requirements,100,2,NOT APPLICABLE,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,interagency_contracting_authority_code,100,1,X,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,interagency_contracting_authority,100,1,NOT APPLICABLE,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,other_statutory_authority,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,program_acronym,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,parent_award_type_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,parent_award_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,parent_award_single_or_multiple_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,parent_award_single_or_multiple,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,major_program,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,national_interest_action_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,national_interest_action,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,cost_or_pricing_data_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,cost_or_pricing_data,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,cost_accounting_standards_clause_code,100,1,X,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,cost_accounting_standards_clause,100,1,NOT APPLICABLE EXEMPT FROM CAS,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,government_furnished_property_code,100,1,N,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,government_furnished_property,100,1,TRANSACTION DOES NOT USE GFE/GFP,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,sea_transportation_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,sea_transportation,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,undefinitized_action_code,13,1,X,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,undefinitized_action,13,1,NO,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,consolidated_contract_code,78,2,D,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,consolidated_contract,78,2,NOT CONSOLIDATED,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,performance_based_service_acquisition_code,100,3,N,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,performance_based_service_acquisition,100,3,NO - SERVICE WHERE PBA IS NOT USED.,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,multi_year_contract_code,12,1,N,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,multi_year_contract,12,1,NO,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,contract_financing_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,contract_financing,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,purchase_card_as_payment_method_code,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,purchase_card_as_payment_method,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,contingency_humanitarian_or_peacekeeping_opera...,1,1,X,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,contingency_humanitarian_or_peacekeeping_opera...,1,1,NOT APPLICABLE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,alaskan_native_corporation_owned_firm,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,american_indian_owned_business,100,2,f,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,indian_tribe_federally_recognized,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,native_hawaiian_organization_owned_firm,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,tribally_owned_firm,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,veteran_owned_business,100,2,f,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,service_disabled_veteran_owned_business,100,2,f,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,woman_owned_business,100,2,f,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,women_owned_small_business,100,2,f,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,economically_disadvantaged_women_owned_small_b...,100,2,f,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,joint_venture_women_owned_small_business,100,2,f,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,joint_venture_economic_disadvantaged_women_own...,100,2,f,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,minority_owned_business,100,2,f,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,subcontinent_asian_asian_indian_american_owned...,100,2,f,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,asian_pacific_american_owned_business,100,2,f,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,black_american_owned_business,100,2,f,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,hispanic_american_owned_business,100,2,f,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,native_american_owned_business,100,2,f,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,other_minority_owned_business,100,2,f,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,contracting_officers_determination_of_business...,100,2,SMALL BUSINESS,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,contracting_officers_determination_of_business...,100,2,S,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,emerging_small_business,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,community_developed_corporation_owned_firm,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,labor_surplus_area_firm,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,us_federal_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,federally_funded_research_and_development_corp,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,federal_agency,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,us_state_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,us_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,city_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,county_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,inter_municipal_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,local_government_owned,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,municipality_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,school_district_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,township_local_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,us_tribal_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,foreign_government,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,organizational_type,97,5,CORPORATE NOT TAX EXEMPT,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,corporate_entity_not_tax_exempt,100,2,t,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,corporate_entity_tax_exempt,100,2,f,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,partnership_or_limited_liability_partnership,100,2,f,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,sole_proprietorship,100,2,f,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,small_agricultural_cooperative,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,international_organization,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,us_government_entity,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,community_development_corporation,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,domestic_shelter,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,educational_institution,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,foundation,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,hospital_flag,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,manufacturer_of_goods,100,2,f,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,veterinary_hospital,100,1,f,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

keep_cols_indices = [
    2, 10, 15, 23, 26, 29, 31, 35, 37, 44, 50, 53, 59, 60, 62, 64, 65, 66, 67, 68, 71,
    109, 110, 144, 159, 161, 163, 176, 187, 186, 187, 194, 195
]

# Add the range from 195 to 296 (inclusive)
keep_cols_indices.extend(range(196, 297))

# Get the column names from the first few rows
temp_df = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', nrows=100)
all_cols = list(temp_df.columns)

# Select the column names based on the indices
keep_cols_names = [all_cols[i] for i in keep_cols_indices if i < len(all_cols)]

# Read the full CSV file, keeping only the specified columns
df_subset = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', usecols=keep_cols_names)

# Display the first few rows of the new dataframe
print(df_subset.head())

# Display info about the new dataframe
df_subset.info()

<ipython-input-29-bbd2867d413a>:17: DtypeWarning: Columns (68,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df_subset = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', usecols=keep_cols_names)

   award_id_piid  total_dollars_obligated  potential_total_value_of_award  \
0  47QSWA20D0092                      0.0                        500000.0
1  47QRAA24D006P                      0.0                        500000.0
2  47QTCA20D008C                      0.0                       4000000.0
3  47QTCA23D0009                      0.0                       7600000.0
4     GS33F004DA                      0.0                        450000.0

  period_of_performance_start_date ordering_period_end_date  \
0                       2020-08-15               2025-08-14
1                       2024-04-17               2029-04-16
2                       2020-04-01               2030-03-31
3                       2022-10-07               2027-10-06
4                       2015-11-03               2025-11-02

              awarding_agency_name     awarding_sub_agency_name  \
0  General Services Administration  Federal Acquisition Service
1  General Services Administration  Federal Acquisition Service
2  General Services Administration  Federal Acquisition Service
3  General Services Administration  Federal Acquisition Service
4  General Services Administration  Federal Acquisition Service

               funding_agency_name      funding_sub_agency_name  \
0  General Services Administration  Federal Acquisition Service
1  General Services Administration  Federal Acquisition Service
2  General Services Administration  Federal Acquisition Service
3  General Services Administration  Federal Acquisition Service
4  General Services Administration  Federal Acquisition Service

  foreign_funding                                     recipient_name  \
0               X                    EVENT HYDRATION SOLUTIONS, INC.
1               X                                          HWW, INC.
2               X  FINANCIAL INSTITUTION INFORMATION SECURITY COM...
3               X                                QUANTUM VETTING INC
4               X                           CLASSIC AIR CHARTER INC.

  cage_code recipient_country_name  recipient_address_line_1  \
0     8AVL8          UNITED STATES     8409 S RANCH ROAD 783
1     51JF6          UNITED STATES       1304 W ROSEBURG AVE
2     74NW7          UNITED STATES  2727 ULMERTON RD STE 310
3     7Y4Y9          UNITED STATES         12040 PARKGATE DR
4     6ZTW9          UNITED STATES       3200 N RIVERSIDE DR

  recipient_city_name recipient_county_name  \
0           KERRVILLE             GILLESPIE
1             MODESTO            STANISLAUS
2          CLEARWATER              PINELLAS
3          NOKESVILLE        PRINCE WILLIAM
4         INDIALANTIC               BREVARD

   prime_award_transaction_recipient_state_fips_code recipient_state_code  \
0                                               48.0                   TX
1                                                6.0                   CA
2                                               12.0                   FL
3                                               51.0                   VA
4                                               12.0                   FL

  recipient_state_name recipient_zip_4_code recipient_phone_number  \
0                TEXAS            780281821           5125631737.0
1           CALIFORNIA            953504855           2093431925.0
2              FLORIDA            337625322           7275711141.0
3             VIRGINIA            201812718           5712616093.0
4              FLORIDA            329034407           3219602445.0

   naics_code                        naics_description  \
0    311423.0  DRIED AND DEHYDRATED FOOD MANUFACTURING
1    541810.0                     ADVERTISING AGENCIES
2    541511.0     CUSTOM COMPUTER PROGRAMMING SERVICES
3    541511.0     CUSTOM COMPUTER PROGRAMMING SERVICES
4    481219.0    OTHER NONSCHEDULED AIR TRANSPORTATION

  small_business_competitiveness_demonstration_program labor_standards  \
0                                                  f    NOT APPLICABLE
1                                                  f               YES
2                                                  f                NO
3                                                  f                NO
4                                                  f               YES

  construction_wage_rate_requirements interagency_contracting_authority  \
0                      NOT APPLICABLE                    NOT APPLICABLE
1                      NOT APPLICABLE                    NOT APPLICABLE
2                      NOT APPLICABLE                    NOT APPLICABLE
3                      NOT APPLICABLE                    NOT APPLICABLE
4                      NOT APPLICABLE                    NOT APPLICABLE

  cost_accounting_standards_clause performance_based_service_acquisition  \
0   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
1   NOT APPLICABLE EXEMPT FROM CAS      YES - SERVICE WHERE PBA IS USED.
2   NOT APPLICABLE EXEMPT FROM CAS   NO - SERVICE WHERE PBA IS NOT USED.
3   NOT APPLICABLE EXEMPT FROM CAS   NO - SERVICE WHERE PBA IS NOT USED.
4   NOT APPLICABLE EXEMPT FROM CAS      YES - SERVICE WHERE PBA IS USED.

  multi_year_contract_code contingency_humanitarian_or_peacekeeping_operation  \
0                      NaN                                                NaN
1                      NaN                                                NaN
2                      NaN                                                NaN
3                      NaN                                                NaN
4                      NaN                                                NaN

  alaskan_native_corporation_owned_firm american_indian_owned_business  \
0                                     f                              f
1                                     f                              f
2                                     f                              f
3                                     f                              f
4                                     f                              f

  indian_tribe_federally_recognized native_hawaiian_organization_owned_firm  \
0                                 f                                       f
1                                 f                                       f
2                                 f                                       f
3                                 f                                       f
4                                 f                                       f

  tribally_owned_firm veteran_owned_business  \
0                   f                      f
1                   f                      f
2                   f                      f
3                   f                      t
4                   f                      f

  service_disabled_veteran_owned_business woman_owned_business  \
0                                       f                    f
1                                       f                    f
2                                       f                    f
3                                       t                    f
4                                       f                    f

  women_owned_small_business  \
0                          f
1                          f
2                          f
3                          f
4                          f

  economically_disadvantaged_women_owned_small_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  joint_venture_women_owned_small_business  \
0                                        f
1                                        f
2                                        f
3                                        f
4                                        f

  joint_venture_economic_disadvantaged_women_owned_small_bus  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  minority_owned_business  \
0                       f
1                       f
2                       f
3                       f
4                       f

  subcontinent_asian_asian_indian_american_owned_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  asian_pacific_american_owned_business black_american_owned_business  \
0                                     f                             f
1                                     f                             f
2                                     f                             f
3                                     f                             f
4                                     f                             f

  hispanic_american_owned_business native_american_owned_business  \
0                                f                              f
1                                f                              f
2                                f                              f
3                                f                              f
4                                f                              f

  other_minority_owned_business  \
0                             f
1                             f
2                             f
3                             f
4                             f

  contracting_officers_determination_of_business_size  \
0                                     SMALL BUSINESS
1                                     SMALL BUSINESS
2                                     SMALL BUSINESS
3                                     SMALL BUSINESS
4                                     SMALL BUSINESS

  contracting_officers_determination_of_business_size_code  \
0                                                  S
1                                                  S
2                                                  S
3                                                  S
4                                                  S

  emerging_small_business community_developed_corporation_owned_firm  \
0                       f                                          f
1                       f                                          f
2                       f                                          f
3                       f                                          f
4                       f                                          f

  labor_surplus_area_firm us_federal_government  \
0                       f                     f
1                       f                     f
2                       f                     f
3                       f                     f
4                       f                     f

  federally_funded_research_and_development_corp federal_agency  \
0                                              f              f
1                                              f              f
2                                              f              f
3                                              f              f
4                                              f              f

  us_state_government us_local_government city_local_government  \
0                   f                   f                     f
1                   f                   f                     f
2                   f                   f                     f
3                   f                   f                     f
4                   f                   f                     f

  county_local_government inter_municipal_local_government  \
0                       f                                f
1                       f                                f
2                       f                                f
3                       f                                f
4                       f                                f

  local_government_owned municipality_local_government  \
0                      f                             f
1                      f                             f
2                      f                             f
3                      f                             f
4                      f                             f

  school_district_local_government township_local_government  \
0                                f                         f
1                                f                         f
2                                f                         f
3                                f                         f
4                                f                         f

  us_tribal_government foreign_government       organizational_type  \
0                    f                  f  CORPORATE NOT TAX EXEMPT
1                    f                  f  CORPORATE NOT TAX EXEMPT
2                    f                  f  CORPORATE NOT TAX EXEMPT
3                    f                  f  CORPORATE NOT TAX EXEMPT
4                    f                  f  CORPORATE NOT TAX EXEMPT

  corporate_entity_not_tax_exempt corporate_entity_tax_exempt  \
0                               t                           f
1                               t                           f
2                               t                           f
3                               t                           f
4                               t                           f

  partnership_or_limited_liability_partnership sole_proprietorship  \
0                                            f                   f
1                                            f                   f
2                                            f                   f
3                                            f                   f
4                                            f                   f

  small_agricultural_cooperative international_organization  \
0                              f                          f
1                              f                          f
2                              f                          f
3                              f                          f
4                              f                          f

  us_government_entity community_development_corporation domestic_shelter  \
0                    f                                 f                f
1                    f                                 f                f
2                    f                                 f                f
3                    f                                 f                f
4                    f                                 f                f

  educational_institution foundation hospital_flag manufacturer_of_goods  \
0                       f          f             f                     t
1                       f          f             f                     f
2                       f          f             f                     f
3                       f          f             f                     f
4                       f          f             f                     f

  veterinary_hospital hispanic_servicing_institution receives_contracts  \
0                   f                              f                  f
1                   f                              f                  f
2                   f                              f                  f
3                   f                              f                  f
4                   f                              f                  f

  receives_financial_assistance receives_contracts_and_financial_assistance  \
0                             f                                           t
1                             f                                           t
2                             f                                           t
3                             f                                           t
4                             f                                           t

  airport_authority council_of_governments housing_authorities_public_tribal  \
0                 f                      f                                 f
1                 f                      f                                 f
2                 f                      f                                 f
3                 f                      f                                 f
4                 f                      f                                 f

  interstate_entity planning_commission port_authority transit_authority  \
0                 f                   f              f                 f
1                 f                   f              f                 f
2                 f                   f              f                 f
3                 f                   f              f                 f
4                 f                   f              f                 f

  subchapter_scorporation limited_liability_corporation foreign_owned  \
0                       f                             f             f
1                       f                             f             f
2                       f                             t             f
3                       t                             f             f
4                       f                             f             f

  for_profit_organization nonprofit_organization  \
0                       t                      f
1                       t                      f
2                       t                      f
3                       t                      f
4                       t                      f

  other_not_for_profit_organization the_ability_one_program  \
0                                 f                       f
1                                 f                       f
2                                 f                       f
3                                 f                       f
4                                 f                       f

  private_university_or_college  \
0                             f
1                             f
2                             f
3                             f
4                             f

  state_controlled_institution_of_higher_learning 1862_land_grant_college  \
0                                               f                       f
1                                               f                       f
2                                               f                       f
3                                               f                       f
4                                               f                       f

  1890_land_grant_college 1994_land_grant_college minority_institution  \
0                       f                       f                    f
1                       f                       f                    f
2                       f                       f                    f
3                       f                       f                    f
4                       f                       f                    f

  historically_black_college tribal_college  \
0                          f              f
1                          f              f
2                          f              f
3                          f              f
4                          f              f

  alaskan_native_servicing_institution native_hawaiian_servicing_institution  \
0                                    f                                     f
1                                    f                                     f
2                                    f                                     f

In [ ]:
df_subset.to_csv('filtered_contracts.csv', index=False)

In [ ]:

keep_cols_indices = [
    2, 10, 15, 23, 26, 29, 31, 35, 37, 44, 50, 53, 59, 60, 62, 64, 65, 66, 67, 68, 71,
    109, 110, 144, 159, 161, 163, 176, 187, 186, 187, 194, 195
]

# Add the range from 195 to 296 (inclusive)
keep_cols_indices.extend(range(196, 297))

# Get the column names from the first few rows
temp_df = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', nrows=100)
all_cols = list(temp_df.columns)

# Select the column names based on the indices
keep_cols_names = [all_cols[i] for i in keep_cols_indices if i < len(all_cols)]

# Read the full CSV file, keeping only the specified columns
df_subset2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', usecols=keep_cols_names)

# Display the first few rows of the new dataframe
print(df_subset2.head())

# Display info about the new dataframe
df_subset2.info()
df_subset2.to_csv('filtered_contracts2.csv', index=False)

<ipython-input-33-8ff5d90c4d14>:17: DtypeWarning: Columns (71) have mixed types. Specify dtype option on import or set low_memory=False.
  df_subset2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', usecols=keep_cols_names)

   award_id_piid  total_dollars_obligated  potential_total_value_of_award  \
0  SPE2DM25FP2GX                   211.68                          211.68
1  47QSWA25P0BWK                  7794.00                         7794.00
2  SPE7LX25FAR59                    10.35                           10.35
3  SPE30025FRFK1                  8902.92                         8902.92
4  SPE8ES25F914R                   173.39                          173.39

  period_of_performance_start_date ordering_period_end_date  \
0                       2025-01-08                      NaN
1                       2025-01-08                      NaN
2                       2025-01-08                      NaN
3                       2025-01-08                      NaN
4                       2025-01-08                      NaN

              awarding_agency_name     awarding_sub_agency_name  \
0            Department of Defense     Defense Logistics Agency
1  General Services Administration  Federal Acquisition Service
2            Department of Defense     Defense Logistics Agency
3            Department of Defense     Defense Logistics Agency
4            Department of Defense     Defense Logistics Agency

               funding_agency_name      funding_sub_agency_name  \
0            Department of Defense     Defense Logistics Agency
1  General Services Administration  Federal Acquisition Service
2            Department of Defense     Defense Logistics Agency
3            Department of Defense     Defense Logistics Agency
4            Department of Defense     Defense Logistics Agency

  foreign_funding                          recipient_name cage_code  \
0               X                CARDINAL HEALTH 200, LLC     07TA6
1               X                F & M MICRO PRODUCTS INC     5RAJ1
2               X    INDEPENDENT ROUGH TERRAIN CENTER LLC     1NWY2
3               X                            US FOODS INC     9P251
4               X  ASRC FEDERAL FACILITIES LOGISTICS, LLC     79343

  recipient_country_name recipient_address_line_1 recipient_city_name  \
0          UNITED STATES        3651 BIRCHWOOD DR            WAUKEGAN
1          UNITED STATES         6917 WOODLEY AVE            VAN NUYS
2          UNITED STATES         103 GUADALUPE DR              CIBOLO
3          UNITED STATES        120 LONGS POND RD           LEXINGTON
4          UNITED STATES          155 PASSAIC AVE           FAIRFIELD

  recipient_county_name  prime_award_transaction_recipient_state_fips_code  \
0                  LAKE                                               17.0
1           LOS ANGELES                                                6.0
2             GUADALUPE                                               48.0
3             LEXINGTON                                               45.0
4                 ESSEX                                               34.0

  recipient_state_code recipient_state_name recipient_zip_4_code  \
0                   IL             ILLINOIS            600858337
1                   CA           CALIFORNIA            914064844
2                   TX                TEXAS            781083144
3                   SC       SOUTH CAROLINA            290729376
4                   NJ           NEW JERSEY            070043561

  recipient_phone_number  naics_code  \
0             8475784883    423450.0
1             8189082080    423710.0
2             2105996541    333120.0
3             2023027119    311999.0
4             7044246912    325520.0

                                   naics_description  \
0  MEDICAL, DENTAL, AND HOSPITAL EQUIPMENT AND SU...
1                      HARDWARE MERCHANT WHOLESALERS
2               CONSTRUCTION MACHINERY MANUFACTURING
3         ALL OTHER MISCELLANEOUS FOOD MANUFACTURING
4                             ADHESIVE MANUFACTURING

  small_business_competitiveness_demonstration_program labor_standards  \
0                                                  f    NOT APPLICABLE
1                                                  f    NOT APPLICABLE
2                                                  f                NO
3                                                  f                NO
4                                                  f    NOT APPLICABLE

  construction_wage_rate_requirements interagency_contracting_authority  \
0                      NOT APPLICABLE                    NOT APPLICABLE
1                      NOT APPLICABLE                    NOT APPLICABLE
2                                  NO                    NOT APPLICABLE
3                                  NO                    NOT APPLICABLE
4                      NOT APPLICABLE                    NOT APPLICABLE

  cost_accounting_standards_clause performance_based_service_acquisition  \
0   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
1                              NaN                        NOT APPLICABLE
2   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
3   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
4   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE

  multi_year_contract_code contingency_humanitarian_or_peacekeeping_operation  \
0                        N                                     NOT APPLICABLE
1                      NaN                                     NOT APPLICABLE
2                        N                                     NOT APPLICABLE
3                        N                                     NOT APPLICABLE
4                        N                                     NOT APPLICABLE

  alaskan_native_corporation_owned_firm american_indian_owned_business  \
0                                     f                              f
1                                     f                              f
2                                     f                              f
3                                     f                              f
4                                     t                              f

  indian_tribe_federally_recognized native_hawaiian_organization_owned_firm  \
0                                 f                                       f
1                                 f                                       f
2                                 f                                       f
3                                 f                                       f
4                                 f                                       f

  tribally_owned_firm veteran_owned_business  \
0                   f                      f
1                   f                      f
2                   f                      f
3                   f                      f
4                   f                      f

  service_disabled_veteran_owned_business woman_owned_business  \
0                                       f                    f
1                                       f                    f
2                                       f                    f
3                                       f                    f
4                                       f                    f

  women_owned_small_business  \
0                          f
1                          f
2                          f
3                          f
4                          f

  economically_disadvantaged_women_owned_small_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  joint_venture_women_owned_small_business  \
0                                        f
1                                        f
2                                        f
3                                        f
4                                        f

  joint_venture_economic_disadvantaged_women_owned_small_bus  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  minority_owned_business  \
0                       f
1                       f
2                       f
3                       f
4                       t

  subcontinent_asian_asian_indian_american_owned_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  asian_pacific_american_owned_business black_american_owned_business  \
0                                     f                             f
1                                     f                             f
2                                     f                             f
3                                     f                             f
4                                     f                             f

  hispanic_american_owned_business native_american_owned_business  \
0                                f                              f
1                                f                              f
2                                f                              f
3                                f                              f
4                                f                              t

  other_minority_owned_business  \
0                             f
1                             f
2                             f
3                             f
4                             f

  contracting_officers_determination_of_business_size  \
0                          OTHER THAN SMALL BUSINESS
1                                     SMALL BUSINESS
2                                     SMALL BUSINESS
3                          OTHER THAN SMALL BUSINESS
4                                     SMALL BUSINESS

  contracting_officers_determination_of_business_size_code  \
0                                                  O
1                                                  S
2                                                  S
3                                                  O
4                                                  S

  emerging_small_business community_developed_corporation_owned_firm  \
0                       f                                          f
1                       f                                          f
2                       f                                          f
3                       f                                          f
4                       f                                          f

  labor_surplus_area_firm us_federal_government  \
0                       f                     f
1                       f                     f
2                       f                     f
3                       f                     f
4                       f                     f

  federally_funded_research_and_development_corp federal_agency  \
0                                              f              f
1                                              f              f
2                                              f              f
3                                              f              f
4                                              f              f

  us_state_government us_local_government city_local_government  \
0                   f                   f                     f
1                   f                   f                     f
2                   f                   f                     f
3                   f                   f                     f
4                   f                   f                     f

  county_local_government inter_municipal_local_government  \
0                       f                                f
1                       f                                f
2                       f                                f
3                       f                                f
4                       f                                f

  local_government_owned municipality_local_government  \
0                      f                             f
1                      f                             f
2                      f                             f
3                      f                             f
4                      f                             f

  school_district_local_government township_local_government  \
0                                f                         f
1                                f                         f
2                                f                         f
3                                f                         f
4                                f                         f

  us_tribal_government foreign_government       organizational_type  \
0                    f                  f                     OTHER
1                    f                  f  CORPORATE NOT TAX EXEMPT
2                    f                  f               PARTNERSHIP
3                    f                  f  CORPORATE NOT TAX EXEMPT
4                    f                  f  CORPORATE NOT TAX EXEMPT

  corporate_entity_not_tax_exempt corporate_entity_tax_exempt  \
0                               f                           f
1                               t                           f
2                               f                           f
3                               t                           f
4                               t                           f

  partnership_or_limited_liability_partnership sole_proprietorship  \
0                                            f                   f
1                                            f                   f
2                                            t                   f
3                                            f                   f
4                                            f                   f

  small_agricultural_cooperative international_organization  \
0                              f                          f
1                              f                          f
2                              f                          f
3                              f                          f
4                              f                          f

  us_government_entity community_development_corporation domestic_shelter  \
0                    f                                 f                f
1                    f                                 f                f
2                    f                                 f                f
3                    f                                 f                f
4                    f                                 f                f

  educational_institution foundation hospital_flag manufacturer_of_goods  \
0                       f          f             f                     f
1                       f          f             f                     f
2                       f          f             f                     t
3                       f          f             f                     f
4                       f          f             f                     f

  veterinary_hospital hispanic_servicing_institution receives_contracts  \
0                   f                              f                  f
1                   f                              f                  f
2                   f                              f                  f
3                   f                              f                  f
4                   f                              f                  f

  receives_financial_assistance receives_contracts_and_financial_assistance  \
0                             f                                           t
1                             f                                           t
2                             f                                           t
3                             f                                           t
4                             f                                           t

  airport_authority council_of_governments housing_authorities_public_tribal  \
0                 f                      f                                 f
1                 f                      f                                 f
2                 f                      f                                 f
3                 f                      f                                 f
4                 f                      f                                 f

  interstate_entity planning_commission port_authority transit_authority  \
0                 f                   f              f                 f
1                 f                   f              f                 f
2                 f                   f              f                 f
3                 f                   f              f                 f
4                 f                   f              f                 f

  subchapter_scorporation limited_liability_corporation foreign_owned  \
0                       f                             t             f
1                       f                             f             f
2                       f                             t             f
3                       f                             f             f
4                       f                             t             f

  for_profit_organization nonprofit_organization  \
0                       t                      f
1                       t                      f
2                       t                      f
3                       t                      f
4                       t                      f

  other_not_for_profit_organization the_ability_one_program  \
0                                 f                       f
1                                 f                       f
2                                 f                       f
3                                 f                       f
4                                 f                       f

  private_university_or_college  \
0                             f
1                             f
2                             f
3                             f
4                             f

  state_controlled_institution_of_higher_learning 1862_land_grant_college  \
0                                               f                       f
1                                               f                       f
2                                               f                       f
3                                               f                       f
4                                               f                       f

  1890_land_grant_college 1994_land_grant_college minority_institution  \
0                       f                       f                    f
1                       f                       f                    f
2                       f                       f                    f
3                       f                       f                    f
4                       f                       f                    f

  historically_black_college tribal_college  \
0                          f              f
1                          f              f
2                          f              f
3                          f              f
4                          f              f

  alaskan_native_servicing_institution native_hawaiian_servicing_institution  \
0                                    f                                     f
1                                    f                                     f
2                                    f                                     f

In [ ]:

keep_cols_indices = [
    2, 10, 15, 23, 26, 29, 31, 35, 37, 44, 50, 53, 59, 60, 62, 64, 65, 66, 67, 68, 71,
    109, 110, 144, 159, 161, 163, 176, 187, 186, 187, 194, 195
]

# Add the range from 195 to 296 (inclusive)
keep_cols_indices.extend(range(196, 297))

# Get the column names from the first few rows
temp_df = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv', nrows=100)
all_cols = list(temp_df.columns)

# Select the column names based on the indices
keep_cols_names = [all_cols[i] for i in keep_cols_indices if i < len(all_cols)]

# Read the full CSV file, keeping only the specified columns
df_subset3 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv', usecols=keep_cols_names)

# Display the first few rows of the new dataframe
print(df_subset3.head())

# Display info about the new dataframe
df_subset3.info()
df_subset3.to_csv('filtered_contracts3.csv', index=False)

<ipython-input-34-ee8ae4957674>:17: DtypeWarning: Columns (71) have mixed types. Specify dtype option on import or set low_memory=False.
  df_subset3 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv', usecols=keep_cols_names)

   award_id_piid  total_dollars_obligated  potential_total_value_of_award  \
0  SPE2DV25FG9P1                  1036.21                         1036.21
1  36F79725D0010                     0.00                       225000.00
2  N6523625F0013               2905784.41                      2905784.41
3  SPE4A625FA7DB                   151.98                          151.98
4  47QSSC25F11PD                   410.04                          410.04

  period_of_performance_start_date ordering_period_end_date  \
0                       2024-10-31                      NaN
1                       2024-11-01               2029-10-31
2                       2024-10-18                      NaN
3                       2024-10-31                      NaN
4                       2024-10-31                      NaN

              awarding_agency_name        awarding_sub_agency_name  \
0            Department of Defense        Defense Logistics Agency
1   Department of Veterans Affairs  Department of Veterans Affairs
2            Department of Defense          Department of the Navy
3            Department of Defense        Defense Logistics Agency
4  General Services Administration     Federal Acquisition Service

               funding_agency_name         funding_sub_agency_name  \
0            Department of Defense        Defense Logistics Agency
1   Department of Veterans Affairs  Department of Veterans Affairs
2            Department of Defense          Department of the Navy
3            Department of Defense        Defense Logistics Agency
4  General Services Administration     Federal Acquisition Service

  foreign_funding                         recipient_name cage_code  \
0               X               CARDINAL HEALTH 200, LLC     07TA6
1               X  HALLIE'S HELPING HANDS HOME CARE, LLC     9H5F5
2               X                         VT MILCOM INC.     66257
3               X          SIKORSKY AIRCRAFT CORPORATION     78286
4               X      NATIONAL INDUSTRIES FOR THE BLIND     5M888

  recipient_country_name recipient_address_line_1 recipient_city_name  \
0          UNITED STATES        3651 BIRCHWOOD DR            WAUKEGAN
1          UNITED STATES         616 BRITTANY CIR            TOWNSEND
2          UNITED STATES    448 VIKING DR STE 350      VIRGINIA BEACH
3          UNITED STATES             6900 MAIN ST           STRATFORD
4          UNITED STATES         3000 POTOMAC AVE          ALEXANDRIA

   recipient_county_name  prime_award_transaction_recipient_state_fips_code  \
0                   LAKE                                               17.0
1             NEW CASTLE                                               10.0
2  VIRGINIA BEACH (CITY)                                               51.0
3     GREATER BRIDGEPORT                                                9.0
4      ALEXANDRIA (CITY)                                               51.0

  recipient_state_code recipient_state_name recipient_zip_4_code  \
0                   IL             ILLINOIS            600858337
1                   DE             DELAWARE            197349057
2                   VA             VIRGINIA            234527397
3                   CT          CONNECTICUT            066141378
4                   VA             VIRGINIA            223053084

  recipient_phone_number  naics_code  \
0           8477854883.0    423450.0
1           3017938307.0    561320.0
2           7036857500.0    541330.0
3           2033865105.0    336411.0
4           7033100330.0    423850.0

                                   naics_description  \
0  MEDICAL, DENTAL, AND HOSPITAL EQUIPMENT AND SU...
1                            TEMPORARY HELP SERVICES
2                               ENGINEERING SERVICES
3                             AIRCRAFT MANUFACTURING
4  SERVICE ESTABLISHMENT EQUIPMENT AND SUPPLIES M...

  small_business_competitiveness_demonstration_program labor_standards  \
0                                                  f    NOT APPLICABLE
1                                                  f               YES
2                                                  f                NO
3                                                  f    NOT APPLICABLE
4                                                  f    NOT APPLICABLE

  construction_wage_rate_requirements interagency_contracting_authority  \
0                      NOT APPLICABLE                    NOT APPLICABLE
1                      NOT APPLICABLE                    NOT APPLICABLE
2                                  NO                    NOT APPLICABLE
3                      NOT APPLICABLE                    NOT APPLICABLE
4                      NOT APPLICABLE                    NOT APPLICABLE

  cost_accounting_standards_clause performance_based_service_acquisition  \
0   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
1   NOT APPLICABLE EXEMPT FROM CAS   NO - SERVICE WHERE PBA IS NOT USED.
2        YES - CAS CLAUSE INCLUDED      YES - SERVICE WHERE PBA IS USED.
3   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE
4   NOT APPLICABLE EXEMPT FROM CAS                        NOT APPLICABLE

  multi_year_contract_code contingency_humanitarian_or_peacekeeping_operation  \
0                        N                                     NOT APPLICABLE
1                      NaN                                                NaN
2                        N                                     NOT APPLICABLE
3                        N                                     NOT APPLICABLE
4                        N                                     NOT APPLICABLE

  alaskan_native_corporation_owned_firm american_indian_owned_business  \
0                                     f                              f
1                                     f                              f
2                                     f                              f
3                                     f                              f
4                                     f                              f

  indian_tribe_federally_recognized native_hawaiian_organization_owned_firm  \
0                                 f                                       f
1                                 f                                       f
2                                 f                                       f
3                                 f                                       f
4                                 f                                       f

  tribally_owned_firm veteran_owned_business  \
0                   f                      f
1                   f                      f
2                   f                      f
3                   f                      f
4                   f                      f

  service_disabled_veteran_owned_business woman_owned_business  \
0                                       f                    f
1                                       f                    t
2                                       f                    f
3                                       f                    f
4                                       f                    f

  women_owned_small_business  \
0                          f
1                          t
2                          f
3                          f
4                          f

  economically_disadvantaged_women_owned_small_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  joint_venture_women_owned_small_business  \
0                                        f
1                                        f
2                                        f
3                                        f
4                                        f

  joint_venture_economic_disadvantaged_women_owned_small_bus  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  minority_owned_business  \
0                       f
1                       t
2                       f
3                       f
4                       f

  subcontinent_asian_asian_indian_american_owned_business  \
0                                                  f
1                                                  f
2                                                  f
3                                                  f
4                                                  f

  asian_pacific_american_owned_business black_american_owned_business  \
0                                     f                             f
1                                     f                             t
2                                     f                             f
3                                     f                             f
4                                     f                             f

  hispanic_american_owned_business native_american_owned_business  \
0                                f                              f
1                                f                              f
2                                f                              f
3                                f                              f
4                                f                              f

  other_minority_owned_business  \
0                             f
1                             f
2                             f
3                             f
4                             f

  contracting_officers_determination_of_business_size  \
0                          OTHER THAN SMALL BUSINESS
1                                     SMALL BUSINESS
2                          OTHER THAN SMALL BUSINESS
3                          OTHER THAN SMALL BUSINESS
4                          OTHER THAN SMALL BUSINESS

  contracting_officers_determination_of_business_size_code  \
0                                                  O
1                                                  S
2                                                  O
3                                                  O
4                                                  O

  emerging_small_business community_developed_corporation_owned_firm  \
0                       f                                          f
1                       f                                          f
2                       f                                          f
3                       f                                          f
4                       f                                          f

  labor_surplus_area_firm us_federal_government  \
0                       f                     f
1                       f                     f
2                       f                     f
3                       f                     f
4                       f                     f

  federally_funded_research_and_development_corp federal_agency  \
0                                              f              f
1                                              f              f
2                                              f              f
3                                              f              f
4                                              f              f

  us_state_government us_local_government city_local_government  \
0                   f                   f                     f
1                   f                   f                     f
2                   f                   f                     f
3                   f                   f                     f
4                   f                   f                     f

  county_local_government inter_municipal_local_government  \
0                       f                                f
1                       f                                f
2                       f                                f
3                       f                                f
4                       f                                f

  local_government_owned municipality_local_government  \
0                      f                             f
1                      f                             f
2                      f                             f
3                      f                             f
4                      f                             f

  school_district_local_government township_local_government  \
0                                f                         f
1                                f                         f
2                                f                         f
3                                f                         f
4                                f                         f

  us_tribal_government foreign_government       organizational_type  \
0                    f                  f                     OTHER
1                    f                  f  CORPORATE NOT TAX EXEMPT
2                    f                  f  CORPORATE NOT TAX EXEMPT
3                    f                  f  CORPORATE NOT TAX EXEMPT
4                    f                  f      CORPORATE TAX EXEMPT

  corporate_entity_not_tax_exempt corporate_entity_tax_exempt  \
0                               f                           f
1                               t                           f
2                               t                           f
3                               t                           f
4                               f                           t

  partnership_or_limited_liability_partnership sole_proprietorship  \
0                                            f                   f
1                                            f                   f
2                                            f                   f
3                                            f                   f
4                                            f                   f

  small_agricultural_cooperative international_organization  \
0                              f                          f
1                              f                          f
2                              f                          f
3                              f                          f
4                              f                          f

  us_government_entity community_development_corporation domestic_shelter  \
0                    f                                 f                f
1                    f                                 f                f
2                    f                                 f                f
3                    f                                 f                f
4                    f                                 f                f

  educational_institution foundation hospital_flag manufacturer_of_goods  \
0                       f          f             f                     f
1                       f          f             f                     f
2                       f          f             f                     f
3                       f          f             f                     f
4                       f          f             f                     t

  veterinary_hospital hispanic_servicing_institution receives_contracts  \
0                   f                              f                  f
1                   f                              f                  f
2                   f                              f                  f
3                   f                              f                  f
4                   f                              f                  f

  receives_financial_assistance receives_contracts_and_financial_assistance  \
0                             f                                           t
1                             f                                           t
2                             f                                           t
3                             f                                           t
4                             f                                           t

  airport_authority council_of_governments housing_authorities_public_tribal  \
0                 f                      f                                 f
1                 f                      f                                 f
2                 f                      f                                 f
3                 f                      f                                 f
4                 f                      f                                 f

  interstate_entity planning_commission port_authority transit_authority  \
0                 f                   f              f                 f
1                 f                   f              f                 f
2                 f                   f              f                 f
3                 f                   f              f                 f
4                 f                   f              f                 f

  subchapter_scorporation limited_liability_corporation foreign_owned  \
0                       f                             t             f
1                       f                             t             f
2                       f                             f             f
3                       f                             f             f
4                       f                             f             f

  for_profit_organization nonprofit_organization  \
0                       t                      f
1                       t                      f
2                       t                      f
3                       t                      f
4                       f                      t

  other_not_for_profit_organization the_ability_one_program  \
0                                 f                       f
1                                 f                       f
2                                 f                       f
3                                 f                       f
4                                 f                       t

  private_university_or_college  \
0                             f
1                             f
2                             f
3                             f
4                             f

  state_controlled_institution_of_higher_learning 1862_land_grant_college  \
0                                               f                       f
1                                               f                       f
2                                               f                       f
3                                               f                       f
4                                               f                       f

  1890_land_grant_college 1994_land_grant_college minority_institution  \
0                       f                       f                    f
1                       f                       f                    f
2                       f                       f                    f
3                       f                       f                    f
4                       f                       f                    f

  historically_black_college tribal_college  \
0                          f              f
1                          f              f
2                          f              f
3                          f              f
4                          f              f

  alaskan_native_servicing_institution native_hawaiian_servicing_institution  \
0                                    f                                     f
1                                    f                                     f
2                                    f                                     f

In [ ]:
df_filtered1 = pd.read_csv('/content/filtered_contracts.csv')
df_filtered2 = pd.read_csv('/content/filtered_contracts2.csv')
df_filtered3 = pd.read_csv('/content/filtered_contracts3.csv')

df_combined = pd.concat([df_filtered1, df_filtered2, df_filtered3], ignore_index=True)
df_combined.info()
print(df_combined.head())
df_combined.to_csv('combined_filtered_contracts.csv', index=True)

<ipython-input-5-5f9dd49645d0>:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filtered1 = pd.read_csv('/content/filtered_contracts.csv')
<ipython-input-5-5f9dd49645d0>:2: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filtered2 = pd.read_csv('/content/filtered_contracts2.csv')
<ipython-input-5-5f9dd49645d0>:3: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filtered3 = pd.read_csv('/content/filtered_contracts3.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500726 entries, 0 to 2500725
Columns: 133 entries, award_id_piid to last_modified_date
dtypes: float64(9), object(124)
memory usage: 2.5+ GB
   award_id_piid  total_dollars_obligated  potential_total_value_of_award  \
0  47QSWA20D0092                      0.0                        500000.0
1  47QRAA24D006P                      0.0                        500000.0
2  47QTCA20D008C                      0.0                       4000000.0
3  47QTCA23D0009                      0.0                       7600000.0
4     GS33F004DA                      0.0                        450000.0

  period_of_performance_start_date ordering_period_end_date  \
0                       2020-08-15               2025-08-14
1                       2024-04-17               2029-04-16
2                       2020-04-01               2030-03-31
3                       2022-10-07               2027-10-06
4                       2015-11-03               2025-11-02

              awarding_agency_name     awarding_sub_agency_name  \
0  General Services Administration  Federal Acquisition Service
1  General Services Administration  Federal Acquisition Service
2  General Services Administration  Federal Acquisition Service
3  General Services Administration  Federal Acquisition Service
4  General Services Administration  Federal Acquisition Service

               funding_agency_name      funding_sub_agency_name  \
0  General Services Administration  Federal Acquisition Service
1  General Services Administration  Federal Acquisition Service
2  General Services Administration  Federal Acquisition Service
3  General Services Administration  Federal Acquisition Service
4  General Services Administration  Federal Acquisition Service

  foreign_funding  ... highly_compensated_officer_2_amount  \
0               X  ...                                 NaN
1               X  ...                                 NaN
2               X  ...                                 NaN
3               X  ...                                 NaN
4               X  ...                                 NaN

  highly_compensated_officer_3_name highly_compensated_officer_3_amount  \
0                               NaN                                 NaN
1                               NaN                                 NaN
2                               NaN                                 NaN
3                               NaN                                 NaN
4                               NaN                                 NaN

  highly_compensated_officer_4_name highly_compensated_officer_4_amount  \
0                               NaN                                 NaN
1                               NaN                                 NaN
2                               NaN                                 NaN
3                               NaN                                 NaN
4                               NaN                                 NaN

  highly_compensated_officer_5_name  highly_compensated_officer_5_amount  \
0                               NaN                                  NaN
1                               NaN                                  NaN
2                               NaN                                  NaN
3                               NaN                                  NaN
4                               NaN                                  NaN

                               usaspending_permalink initial_report_date  \
0  https://www.usaspending.gov/award/CONT_IDV_47Q...          2025-05-03
1  https://www.usaspending.gov/award/CONT_IDV_47Q...          2025-05-03
2  https://www.usaspending.gov/award/CONT_IDV_47Q...          2025-05-03
3  https://www.usaspending.gov/award/CONT_IDV_47Q...          2025-05-03
4  https://www.usaspending.gov/award/CONT_IDV_GS3...          2025-05-03

  last_modified_date
0         2025-05-03
1         2025-05-03
2         2025-05-03
3         2025-05-03
4         2025-05-03

[5 rows x 133 columns]

In [ ]:
df_combined.shape

(2500726, 133)

In [ ]:
df_combined.head(10).transpose().reset_index()

,index,0,1,2,3,4,5,6,7,8,9
0,award_id_piid,47QSWA20D0092,47QRAA24D006P,47QTCA20D008C,47QTCA23D0009,GS33F004DA,47QTCA19D0063,GS03F060AA,47QTCA23D00EN,47QRAA24D00CT,47QSWA22D0036
1,total_dollars_obligated,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,potential_total_value_of_award,500000.0,500000.0,4000000.0,7600000.0,450000.0,6000000.0,708183.0,500000.0,2000000.0,500000.0
3,period_of_performance_start_date,2020-08-15,2024-04-17,2020-04-01,2022-10-07,2015-11-03,2019-02-19,2013-04-01,2023-09-26,2024-08-22,2022-02-11
4,ordering_period_end_date,2025-08-14,2029-04-16,2030-03-31,2027-10-06,2025-11-02,2029-02-18,2028-03-31,2028-09-25,2029-08-21,2027-02-10
5,awarding_agency_name,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration
6,awarding_sub_agency_name,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service
7,funding_agency_name,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration,General Services Administration
8,funding_sub_agency_name,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service,Federal Acquisition Service
9,foreign_funding,X,X,X,X,X,X,X,X,X,X
10,recipient_name,"EVENT HYDRATION SOLUTIONS, INC.","HWW, INC.",FINANCIAL INSTITUTION INFORMATION SECURITY COM...,QUANTUM VETTING INC,CLASSIC AIR CHARTER INC.,FALCON LOGIC LLC,APISOURCE INC,AXUMFED LLC,TOLAND MIZELL MOLNAR LLC,PFC SAFEGUARDS LLC
11,cage_code,8AVL8,51JF6,74NW7,7Y4Y9,6ZTW9,5S5E6,1TEY1,8B1S5,5UF00,6MJU5
12,recipient_country_name,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES,UNITED STATES
13,recipient_address_line_1,8409 S RANCH ROAD 783,1304 W ROSEBURG AVE,2727 ULMERTON RD STE 310,12040 PARKGATE DR,3200 N RIVERSIDE DR,2452 RIDGEHAMPTON CT,7850 WALKER DR STE 400,1765 GREENSBORO STATION PL 9TH FL,512 MEANS ST NW STE 400,2960 E SUNSET RD STE 125
14,recipient_city_name,KERRVILLE,MODESTO,CLEARWATER,NOKESVILLE,INDIALANTIC,RESTON,GREENBELT,MCLEAN,ATLANTA,LAS VEGAS
15,recipient_county_name,GILLESPIE,STANISLAUS,PINELLAS,PRINCE WILLIAM,BREVARD,FAIRFAX,PRINCE GEORGE'S,FAIRFAX,FULTON,CLARK
16,prime_award_transaction_recipient_state_fips_code,48.0,6.0,12.0,51.0,12.0,51.0,24.0,51.0,13.0,32.0
17,recipient_state_code,TX,CA,FL,VA,FL,VA,MD,VA,GA,NV
18,recipient_state_name,TEXAS,CALIFORNIA,FLORIDA,VIRGINIA,FLORIDA,VIRGINIA,MARYLAND,VIRGINIA,GEORGIA,NEVADA
19,recipient_zip_4_code,780281821,953504855,337625322,201812718,329034407,201912826,207703240,221023472,303185788,891202753
20,recipient_phone_number,5125631737.0,2093431925.0,7275711141.0,5712616093.0,3219602445.0,8773032526.0,3017316100.0,5403385071.0,4042149774.0,7026471126.0
21,naics_code,311423.0,541810.0,541511.0,541511.0,481219.0,541511.0,423910.0,541519.0,541330.0,561612.0
22,naics_description,DRIED AND DEHYDRATED FOOD MANUFACTURING,ADVERTISING AGENCIES,CUSTOM COMPUTER PROGRAMMING SERVICES,CUSTOM COMPUTER PROGRAMMING SERVICES,OTHER NONSCHEDULED AIR TRANSPORTATION,CUSTOM COMPUTER PROGRAMMING SERVICES,SPORTING AND RECREATIONAL GOODS AND SUPPLIES M...,OTHER COMPUTER RELATED SERVICES,ENGINEERING SERVICES,SECURITY GUARDS AND PATROL SERVICES
23,small_business_competitiveness_demonstration_p...,f,f,f,f,f,f,f,f,f,f
24,labor_standards,NOT APPLICABLE,YES,NO,NO,YES,NO,NOT APPLICABLE,NO,YES,YES
25,construction_wage_rate_requirements,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE
26,interagency_contracting_authority,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE,NOT APPLICABLE
27,cost_accounting_standards_clause,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS,NOT APPLICABLE EXEMPT FROM CAS
28,performance_based_service_acquisition,NOT APPLICABLE,YES - SERVICE WHERE PBA IS USED.,NO - SERVICE WHERE PBA IS NOT USED.,NO - SERVICE WHERE PBA IS NOT USED.,YES - SERVICE WHERE PBA IS USED.,YES - SERVICE WHERE PBA IS USED.,NOT APPLICABLE,NO - SERVICE WHERE PBA IS NOT USED.,YES - SERVICE WHERE PBA IS USED.,YES - SERVICE WHERE PBA IS USED.
29,multi_year_contract_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,contingency_humanitarian_or_peacekeeping_opera...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,alaskan_native_corporation_owned_firm,f,f,f,f,f,f,f,f,f,f
32,american_indian_owned_business,f,f,f,f,f,f,f,f,f,f
33,indian_tribe_federally_recognized,f,f,f,f,f,f,f,f,f,f
34,native_hawaiian_organization_owned_firm,f,f,f,f,f,f,f,f,f,f
35,tribally_owned_firm,f,f,f,f,f,f,f,f,f,f
36,veteran_owned_business,f,f,f,t,f,f,f,f,t,t
37,service_disabled_veteran_owned_business,f,f,f,t,f,f,f,f,t,t
38,woman_owned_business,f,f,f,f,f,t,t,t,f,f
39,women_owned_small_business,f,f,f,f,f,t,f,t,f,f
40,economically_disadvantaged_women_owned_small_b...,f,f,f,f,f,t,f,t,f,f
41,joint_venture_women_owned_small_business,f,f,f,f,f,f,f,t,f,f
42,joint_venture_economic_disadvantaged_women_own...,f,f,f,f,f,f,f,t,f,f
43,minority_owned_business,f,f,f,f,f,t,f,t,f,f
44,subcontinent_asian_asian_indian_american_owned...,f,f,f,f,f,t,f,t,f,f
45,asian_pacific_american_owned_business,f,f,f,f,f,f,f,f,f,f
46,black_american_owned_business,f,f,f,f,f,f,f,f,f,f
47,hispanic_american_owned_business,f,f,f,f,f,f,f,f,f,f
48,native_american_owned_business,f,f,f,f,f,f,f,f,f,f
49,other_minority_owned_business,f,f,f,f,f,f,f,f,f,f
50,contracting_officers_determination_of_business...,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS,SMALL BUSINESS
51,contracting_officers_determination_of_business...,S,S,S,S,S,S,S,S,S,S
52,emerging_small_business,f,f,f,f,f,f,f,f,f,f
53,community_developed_corporation_owned_firm,f,f,f,f,f,f,f,f,f,f
54,labor_surplus_area_firm,f,f,f,f,f,f,f,f,f,f
55,us_federal_government,f,f,f,f,f,f,f,f,f,f
56,federally_funded_research_and_development_corp,f,f,f,f,f,f,f,f,f,f
57,federal_agency,f,f,f,f,f,f,f,f,f,f
58,us_state_government,f,f,f,f,f,f,f,f,f,f
59,us_local_government,f,f,f,f,f,f,f,f,f,f
60,city_local_government,f,f,f,f,f,f,f,f,f,f
61,county_local_government,f,f,f,f,f,f,f,f,f,f
62,inter_municipal_local_government,f,f,f,f,f,f,f,f,f,f
63,local_government_owned,f,f,f,f,f,f,f,f,f,f
64,municipality_local_government,f,f,f,f,f,f,f,f,f,f
65,school_district_local_government,f,f,f,f,f,f,f,f,f,f
66,township_local_government,f,f,f,f,f,f,f,f,f,f
67,us_tribal_government,f,f,f,f,f,f,f,f,f,f
68,foreign_government,f,f,f,f,f,f,f,f,f,f
69,organizational_type,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,OTHER,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT,CORPORATE NOT TAX EXEMPT
70,corporate_entity_not_tax_exempt,t,t,t,t,t,f,t,t,t,t
71,corporate_entity_tax_exempt,f,f,f,f,f,f,f,f,f,f
72,partnership_or_limited_liability_partnership,f,f,f,f,f,f,f,f,f,f
73,sole_proprietorship,f,f,f,f,f,f,f,f,f,f
74,small_agricultural_cooperative,f,f,f,f,f,f,f,f,f,f
75,international_organization,f,f,f,f,f,f,f,f,f,f
76,us_government_entity,f,f,f,f,f,f,f,f,f,f
77,community_development_corporation,f,f,f,f,f,f,f,f,f,f
78,domestic_shelter,f,f,f,f,f,f,f,f,f,f
79,educational_institution,f,f,f,f,f,f,f,f,f,f
80,foundation,f,f,f,f,f,f,f,f,f,f
81,hospital_flag,f,f,f,f,f,f,f,f,f,f
82,manufacturer_of_goods,t,f,f,f,f,f,t,f,f,f
83,veterinary_hospital,f,f,f,f,f,f,f,f,f,f
84,hispanic_servicing_institution,f,f,f,f,f,f,f,f,f,f
85,receives_contracts,f,f,f,f,f,f,f,f,f,f
86,receives_financial_assistance,f,f,f,f,f,f,f,f,f,f
87,receives_contracts_and_financial_assistance,t,t,t,t,t,t,t,t,t,t
88,airport_authority,f,f,f,f,f,f,f,f,f,f
89,council_of_governments,f,f,f,f,f,f,f,f,f,f
90,housing_authorities_public_tribal,f,f,f,f,f,f,f,f,f,f
91,interstate_entity,f,f,f,f,f,f,f,f,f,f
92,planning_commission,f,f,f,f,f,f,f,f,f,f
93,port_authority,f,f,f,f,f,f,f,f,f,f
94,transit_authority,f,f,f,f,f,f,f,f,f,f
95,subchapter_scorporation,f,f,f,t,f,f,f,f,f,f
96,limited_liability_corporation,f,f,t,f,f,t,f,t,t,t
97,foreign_owned,f,f,f,f,f,f,f,f,f,f
98,for_profit_organization,t,t,t,t,t,t,t,t,t,t
99,nonprofit_organization,f,f,f,f,f,f,f,f,f,f
100,other_not_for_profit_organization,f,f,f,f,f,f,f,f,f,f
101,the_ability_one_program,f,f,f,f,f,f,f,f,f,f
102,private_university_or_college,f,f,f,f,f,f,f,f,f,f
103,state_controlled_institution_of_higher_learning,f,f,f,f,f,f,f,f,f,f
104,1862_land_grant_college,f,f,f,f,f,f,f,f,f,f
105,1890_land_grant_college,f,f,f,f,f,f,f,f,f,f
106,1994_land_grant_college,f,f,f,f,f,f,f,f,f,f
107,minority_institution,f,f,f,f,f,f,f,f,f,f
108,historically_black_college,f,f,f,f,f,f,f,f,f,f
109,tribal_college,f,f,f,f,f,f,f,f,f,f
110,alaskan_native_servicing_institution,f,f,f,f,f,f,f,f,f,f
111,native_hawaiian_servicing_institution,f,f,f,f,f,f,f,f,f,f
112,school_of_forestry,f,f,f,f,f,f,f,f,f,f
113,veterinary_college,f,f,f,f,f,f,f,f,f,f
114,dot_certified_disadvantage,f,f,f,f,f,f,f,f,f,f
115,self_certified_small_disadvantaged_business,f,t,f,f,f,t,f,t,f,f
116,small_disadvantaged_business,f,f,f,f,f,f,f,f,f,f
117,c8a_program_participant,f,f,f,f,f,f,f,f,f,f
118,historically_underutilized_business_zone_hubzo...,f,f,f,f,f,f,f,f,f,f
119,sba_certified_8a_joint_venture,f,f,f,f,f,f,f,f,f,f
120,highly_compensated_officer_1_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,highly_compensated_officer_1_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,highly_compensated_officer_2_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,highly_compensated_officer_2_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,highly_compensated_officer_3_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,highly_compensated_officer_3_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,highly_compensated_officer_4_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,highly_compensated_officer_4_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,highly_compensated_officer_5_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,highly_compensated_officer_5_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,usaspending_permalink,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_GS3...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_GS0...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_47Q...,https://www.usaspending.gov/award/CONT_IDV_47Q...
131,initial_report_date,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03
132,last_modified_date,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03,2025-05-03

In [ ]:
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [ ]:
df_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 133 entries, award_id_piid to last_modified_date
dtypes: float64(9), object(124)
memory usage: 1014.7+ MB

In [ ]:
df_subset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 133 entries, award_id_piid to last_modified_date
dtypes: float64(9), object(124)
memory usage: 1014.7+ MB

In [ ]:
df_subset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500726 entries, 0 to 500725
Columns: 133 entries, award_id_piid to last_modified_date
dtypes: float64(9), object(124)
memory usage: 508.1+ MB

In [ ]:
df1 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', nrows=500_000)

<ipython-input-2-f6a00191ef57>:1: DtypeWarning: Columns (5,47,68,71,72,81,107,108,115,116,117,118,135,136,165,171,172,179,180) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', nrows=500_000)

In [ ]:
df2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', skiprows=500_000, header=None)

<ipython-input-3-db00d4cad4a3>:1: DtypeWarning: Columns (5,47,68,71,72,81,107,108,115,116,135,136,164,165,179,180) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_1.csv', skiprows=500_000, header=None)

In [ ]:
df1.to_parquet('df1.parquet')
#df2.to_parquet('df2.parquet')

ArrowTypeError: ("Expected bytes, got a 'float' object", 'Conversion failed for column parent_award_agency_id with type object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Columns: 297 entries, contract_transaction_unique_key to last_modified_date
dtypes: float64(28), int64(3), object(266)
memory usage: 1.1+ GB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Columns: 297 entries, 12C2_4732_12318724F0301_P00001_47QTCA20D00B1_0 to 2025-02-11.1
dtypes: float64(30), int64(3), object(264)
memory usage: 1.1+ GB

In [ ]:
df2.tail()

,12C2_4732_12318724F0301_P00001_47QTCA20D00B1_0,CONT_AWD_12318724F0301_12C2_47QTCA20D00B1_4732,12318724F0301,P00001,0,4732,FEDERAL ACQUISITION SERVICE,47QTCA20D00B1,PA0002,100000.00,...,Unnamed: 287,Unnamed: 288,Unnamed: 289,Unnamed: 290,Unnamed: 291,Unnamed: 292,Unnamed: 293,https://www.usaspending.gov/award/CONT_AWD_12318724F0301_12C2_47QTCA20D00B1_4732/,2025-02-10,2025-02-11.1
499995,9700_9700_SPE2D625F17MW_0_SPE2DE24D0021_0,CONT_AWD_SPE2D625F17MW_9700_SPE2DE24D0021_9700,SPE2D625F17MW,0,0.0,9700,DEPT OF DEFENSE,SPE2DE24D0021,0,94.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_SPE...,2025-01-08,2025-01-16
499996,12C2_12C2_1240BE24F0035_P00002_1204N020A0048_0,CONT_AWD_1240BE24F0035_12C2_1204N020A0048_12C2,1240BE24F0035,P00002,0.0,12C2,FOREST SERVICE,1204N020A0048,0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_124...,2025-01-08,2025-01-08
499997,4732_-NONE-_47QSSC25P0HJV_0_-NONE-_0,CONT_AWD_47QSSC25P0HJV_4732_-NONE-_-NONE-,47QSSC25P0HJV,0,0.0,NaN,NaN,NaN,NaN,80.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_47Q...,2025-01-09,2025-01-09
499998,9700_9700_SPE30025FRF5C_0_SPE30025DV002_0,CONT_AWD_SPE30025FRF5C_9700_SPE30025DV002_9700,SPE30025FRF5C,0,0.0,9700,DEPT OF DEFENSE,SPE30025DV002,0,242.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_SPE...,2025-01-08,2025-03-21
499999,1540_1540_15B61225F00000020_0_15B61220D00000001_0,CONT_AWD_15B61225F00000020_1540_15B61220D00000...,15B61225F00000020,0,0.0,1540,FEDERAL PRISON SYSTEM / BUREAU OF PRISONS,15B61220D00000001,0,6000.00,...,240000.0,BRYAN HEFTLER,156402.0,BOBBIE J HEFTLER,187722.0,GREGORY J BARBEREE,187000.0,https://www.usaspending.gov/award/CONT_AWD_15B...,2025-01-08,2025-01-08

In [ ]:
df4 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', nrows=500_000)

<ipython-input-13-c8c35ef9c0c5>:1: DtypeWarning: Columns (5,47,71,72,81,115,135,136,164,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df4 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', nrows=500_000)

In [ ]:
df5 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv', skiprows=500_000, header=None)

TypeError: read_csv() got an unexpected keyword argument 'headers'

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 297 entries, contract_transaction_unique_key to last_modified_date
dtypes: float64(84), int64(6), object(207)
memory usage: 232.2+ KB

In [ ]:
df2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv')

<ipython-input-8-9cc200530812>:1: DtypeWarning: Columns (5,47,71,72,81,115,135,136,164,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_2.csv')

In [ ]:
df3 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv')

<ipython-input-3-ad108dc0422d>:1: DtypeWarning: Columns (5,47,71,72,81,115,135,136,164,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv('./FY2025_All_Contracts_Full_20250508_3.csv')

In [ ]:
full_contracts = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)

full_contracts.drop_duplicates(inplace=True)

print(full_contracts.head())
#full_contracts.info()

**Savings**

In [ ]:
# grants

In [ ]:
#contracts

In [ ]:
#leases

**Payments**

In [ ]:
#payments

In [ ]:
#statistics

GITHUB

In [ ]:
# import data from url and view as data frame

import pandas as pd

# Define the URL of the CSV file
url = 'https://github.com/etmcrae/DOGE-Clone/blob/main/data/doge-contract.csv'

# Read the CSV data from the URL into a pandas DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
print(df.head())

ParserError: Error tokenizing data. C error: Expected 1 fields in line 43, saw 66

In [ ]:
import requests

url = 'https://github.com/etmcrae/DOGE-Clone/blob/main/data/doge-contract.csv'
url.split('/')[-1]

print(content)

<!DOCTYPE html>
<html
  lang="en"

  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"

  >



  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">




  <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/light-74231a1f3bbb.css" /><link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/light_high_contrast-83beb16e0ecf.css" /><link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/dark-8a995f0bacd4.css" /><link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/dark_high_contrast-9ac301c3ebe5.css" /><link data-color-theme="light" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light-74231a1f3bbb.css" /><link data-color-theme="light_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_high_contrast-83beb16e0ecf.css" /><link data-color-theme="light_colorblind" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_colorblind-f91b0f603451.css" /><link data-color-theme="light_colorblind_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_colorblind_high_contrast-5aebfa54b215.css" /><link data-color-theme="light_tritanopia" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_tritanopia-6e122dab64fc.css" /><link data-color-theme="light_tritanopia_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/light_tritanopia_high_contrast-b32664e28b79.css" /><link data-color-theme="dark" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark-8a995f0bacd4.css" /><link data-color-theme="dark_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_high_contrast-9ac301c3ebe5.css" /><link data-color-theme="dark_colorblind" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_colorblind-cd826e8636dc.css" /><link data-color-theme="dark_colorblind_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_colorblind_high_contrast-131d53fe187c.css" /><link data-color-theme="dark_tritanopia" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_tritanopia-18119e682df0.css" /><link data-color-theme="dark_tritanopia_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_tritanopia_high_contrast-63c0358957ba.css" /><link data-color-theme="dark_dimmed" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_dimmed-f37fb7684b1f.css" /><link data-color-theme="dark_dimmed_high_contrast" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_dimmed_high_contrast-8f371c75debd.css" />

    <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/primer-primitives-225433424a87.css" />
    <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/primer-b8b91660c29d.css" />
    <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/global-3ccbd788fe33.css" />
    <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/github-685f3d1c0424.css" />
  <link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/repository-197a21528ff0.css" />
<link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/code-177d21388df8.css" />




  <script type="application/json" id="client-env">{"locale":"en","featureFlags":["alternate_user_config_repo","api_insights_show_missing_data_banner","codespaces_prebuild_region_target_update","contentful_lp_flex_features_actions","contentful_lp_flex_features_code_review","contentful_lp_flex_features_code_search","contentful_lp_flex_features_codespaces","contentful_lp_flex_features_discussions","contentful_lp_flex_features_issues","contentful_lp_footnotes","copilot_chat_custom_instructions","copilot_chat_repo_custom_instructions_preview","copilot_chat_vision_in_claude","copilot_chat_wholearea_dd","copilot_duplicate_thread","copilot_free_to_paid_telem","copilot_header_button_to_immersive","copilot_immersive_draft_issue_metadata_location","copilot_immersive_draft_issue_template_required","copilot_immersive_issue_preview","copilot_new_immersive_references_ui","copilot_no_floating_button","copilot_read_shared_conversation","copilot_scroll_container_query","copilot_showcase_icebreakers","copilot_task_oriented_assistive_prompts","copilot_topics_as_references","copilot_ui_refs","direct_to_salesforce","dotcom_chat_client_side_skills","ghost_pilot_confidence_truncation_25","ghost_pilot_confidence_truncation_40","github_models_grok_3_mini_json","github_models_grok_3_mini_json_schema","github_models_o3_streaming","insert_before_patch","issues_dashboard_no_redirects","issues_react_blur_item_picker_on_close","issues_react_create_milestone","issues_react_dashboard_save_query_refresh","issues_react_prohibit_title_fallback","issues_react_remove_placeholders","lifecycle_label_name_updates","link_contact_sales_swp_marketo","marketing_pages_search_explore_provider","memex_mwl_filter_field_delimiter","nonreporting_relay_graphql_status_codes","primer_react_css_modules_ga","primer_react_select_panel_with_modern_action_list","remove_child_patch","sample_network_conn_type","site_msbuild_hide_integrations","site_msbuild_launch","site_msbuild_webgl_hero","site_proxima_australia_update","site_proxima_usa_update","swp_enterprise_contact_form","use_copilot_avatar","use_paginated_repo_picker_cost_center_form","viewscreen_sandbox"]}</script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/wp-runtime-1fd0995bd64f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_oddbird_popover-polyfill_dist_popover-fn_js-81211bd82278.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_mini-throttle_dist_index_js-node_modules_stacktrace-parser_dist_s-1d3d52-4be8ffe9a34a.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_failbot_failbot_ts-f0df83c858f4.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/environment-d607485791a5.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_primer_behaviors_dist_esm_index_mjs-0dbb79f97f8f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_selector-observer_dist_index_esm_js-f690fd9ae3d5.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_relative-time-element_dist_index_js-fd884d19bf73.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_text-expander-element_dist_index_js-78748950cb0c.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_auto-complete-element_dist_index_js-node_modules_github_catalyst_-8e9f78-a90ac05d2469.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_filter-input-element_dist_index_js-node_modules_github_remote-inp-d8c643-f5192902810f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_markdown-toolbar-element_dist_index_js-ceef33f593fa.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_mini-throttle_dist_index_js-node_modules_github_combobox-nav_dist-97536f-0a0158d4c78e.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_file-attachment-element_dist_index_js-node_modules_primer_view-co-63644b-8389d8c5493d.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/github-elements-2c6b561fd398.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/element-registry-759bd527e556.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_braintree_browser-detection_dist_browser-detection_js-node_modules_githu-bb80ec-72267f4e3ff9.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_lit-html_lit-html_js-be8cb88f481b.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_morphdom_dist_morphdom-esm_js-0c08218c7d5f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_fzy_js_index_js-node_modules_github_paste-markdown_dist_index_js-6c00013a3dc4.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_turbo_dist_turbo_es2017-esm_js-a03ee12d659a.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_remote-form_dist_index_js-node_modules_delegated-events_dist_inde-893f9f-b6294cf703b7.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_color-convert_index_js-e3180fe3bcb3.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_quote-selection_dist_index_js-node_modules_github_session-resume_-c1aa61-97c8ff49bc41.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_updatable-content_updatable-content_ts-f4e60782b52d.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/app_assets_modules_github_behaviors_task-list_ts-app_assets_modules_github_sso_ts-ui_packages-900dde-c84fbefd392e.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/app_assets_modules_github_sticky-scroll-into-view_ts-3e000c5d31a9.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/app_assets_modules_github_behaviors_ajax-error_ts-app_assets_modules_github_behaviors_include-d0d0a6-9dc4ed803189.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/app_assets_modules_github_behaviors_commenting_edit_ts-app_assets_modules_github_behaviors_ht-83c235-ce8979e4f922.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/behaviors-26f5fa9fe37f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_delegated-events_dist_index_js-node_modules_github_catalyst_lib_index_js-ea8eaa-ae0dbe787ad8.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/notifications-global-7f3748c0d76b.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_mini-throttle_dist_index_js-node_modules_github_catalyst_lib_inde-dbbea9-4adcaf6c1c40.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/code-menu-906f56af9b01.js"></script>

  <script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/primer-react-5c26f1a581a7.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/react-core-2d17b940397e.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/react-lib-80430c87778a.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/octicons-react-cf2f2ab8dab4.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_emotion_is-prop-valid_dist_emotion-is-prop-valid_esm_js-node_modules_emo-b1c483-30bc59af3a76.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_github_catalyst_lib_index_js-node_modules_primer_live-region-element_dis-b2aea6-22827f205bdc.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_dompurify_dist_purify_es_mjs-dd1d3ea6a436.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_lodash-es__Stack_js-node_modules_lodash-es__Uint8Array_js-node_modules_l-4faaa6-4a736fde5c2f.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_lodash-es_isEqual_js-92a85ab8c568.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_tanstack_react-virtual_dist_esm_index_js-node_modules_react-virtual_dist-19a6be-f0cf337af5df.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_focus-visible_dist_focus-visible_js-node_modules_github_hydro-analytics--e21ffd-3c9d2ac3e1ad.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/vendors-node_modules_fzy_js_index_js-node_modules_react-reverse-portal_dist_web_index_js-node-e0551b-12901247dcff.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_document-metadata_document-metadata_ts-ui_packages_history_history_ts-ui_packages-417c81-50b9bb07478c.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_paths_index_ts-3d2b07827323.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_ref-selector_RefSelector_tsx-cd14487ff967.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_commit-attribution_index_ts-ui_packages_commit-checks-status_index_ts-ui_packages-762eaa-b9321ed019f0.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_app-uuid_app-uuid_ts-ui_packages_repos-file-tree-view_repos-file-tree-view_ts-4239cbf37c05.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_hydro-analytics_hydro-analytics_ts-ui_packages_use-client-value_use-client-value_-6f712e-d59b35038b54.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/ui_packages_code-view-shared_hooks_use-canonical-object_ts-ui_packages_code-view-shared_hooks-7b64b1-e9366a95354b.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/app_assets_modules_github_blob-anchor_ts-ui_packages_code-nav_code-nav_ts-ui_packages_filter--8253c1-91468a3354f9.js"></script>
<script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/react-code-view-cdf73e330df5.js"></script>
<link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/primer-react.19291721a114332ad118.module.css" />
<link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/react-code-view.3904ff40d7b98a92de4b.module.css" />

  <script crossorigin="anonymous" defer="defer" type="application/javascript" src="https://github.githubassets.com/assets/notifications-subscriptions-menu-289430569e8f.js"></script>
<link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/primer-react.19291721a114332ad118.module.css" />
<link crossorigin="anonymous" media="all" rel="stylesheet" href="https://github.githubassets.com/assets/notifications-subscriptions-menu.e5e6e593370c808590a5.module.css" />


  <title>DOGE-Clone/data/doge-contract.csv at main · etmcrae/DOGE-Clone · GitHub</title>



  <meta name="route-pattern" content="/:user_id/:repository/blob/*name(/*path)" data-turbo-transient>
  <meta name="route-controller" content="blob" data-turbo-transient>
  <meta name="route-action" content="show" data-turbo-transient>
  <meta name="fetch-nonce" content="v2:2c24cda1-c987-b293-c846-4ef6e2fac2ef">


  <meta name="current-catalog-service-hash" content="f3abb0cc802f3d7b95fc8762b94bdcb13bf39634c40c357301c4aa1d67a256fb">



In [ ]:
combined_filtered_contracts.head()

NameError: name 'combined_filtered_contracts' is not defined

In [ ]:
combined_filtered_contracts.head(10).transpose()

NameError: name 'combined_filtered_contracts' is not defined

In [ ]:
combined_filtered_contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500726 entries, 0 to 2500725
Columns: 133 entries, award_id_piid to last_modified_date
dtypes: float64(9), object(124)
memory usage: 2.5+ GB

In [ ]:
filtered_contracts.csv

In [ ]:
combined_filtered_contracts.head

NameError: name 'combined_filtered_contracts' is not defined

In [ ]:
# prompt: curl -X 'GET' \
#   'https://api.doge.gov/savings/contracts?per_page=500' \
#   -H 'accept: application/json'
import requests
url = 'https://api.doge.gov/savings/contracts?per_page=500'
headers = {'accept': 'application/json'}

response = requests.get(url, headers=headers)

if response.status_code == 200:
  data = response.json()
  # You can now work with the JSON data in the 'data' variable
  print("Successfully fetched data from the API.")
  # Example: print the first item in the results list if it exists
  if data and 'results' in data and data['results']:
    print("First result:", data['results'][0])
else:
  print(f"Error fetching data. Status code: {response.status_code}")
  print("Response body:", response.text)

Successfully fetched data from the API.

In [ ]:
# data from api save to a df called DOGE
dfs = []
for i in range (1, 24):

  url = f'https://api.doge.gov/savings/contracts?page={i}&per_page=500'
  headers = {'accept': 'application/json'}

  response = requests.get(url, headers=headers)

  if response.status_code == 200:
    data = response.json()
    # Assuming the data is in a 'results' key in the JSON response
    if data and 'result' in data:
      DOGE = pd.DataFrame(data['result']['contracts'])
      dfs.append(DOGE)
      print("Successfully created DataFrame DOGE.")
      print(DOGE.head())
    else:
      print("API response does not contain 'results' key.")
  else:
    print(f"Error fetching data. Status code: {response.status_code}")
    print("Response body:", response.text)

Successfully created DataFrame DOGE.
             piid                                   agency  \
0  2032H824F00058                   Department of Treasury
1  20341522F00039                   Department of Treasury
2  75D30124F19709  Department of Health and Human Services
3     Unavailable                                    USAID
4   95170024C0273    United States Agency for Global Media

                           vendor         value  \
0         DELOITTE CONSULTING LLP  7.259739e+06
1             FI CONSULTING, INC.  2.992678e+06
2     FAMILY HEALTH INTERNATIONAL  1.428250e+08
3                     Unavailable  9.499996e+07
4  MISCELLANEOUS FOREIGN AWARDEES  1.767699e+07

                                         description  fpds_status  \
0  Comprehensive Training Strategy aimed at enhan...   TERMINATED
1            Independent Verification and Validation   TERMINATED
2  HUMAN IMMUNODEFICIENCY VIRUS COMMUNICATIONS PR...   TERMINATED
3                      Unavailable for legal reasons  Unavailable
4  MEDIUM WAVE RADIO BROADCASTING TRANSMISSION SE...   TERMINATED

                                           fpds_link deleted_date  \
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     6/3/2025
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     6/3/2025
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     6/3/2025
3                                   https://fpds.gov     6/3/2025
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     6/3/2025

        savings
0  4.354402e+06
1  0.000000e+00
2  1.245576e+08
3  6.524996e+07
4  1.608278e+07
Successfully created DataFrame DOGE.
                piid                                   agency  \
0     75D30123C17004  Department of Health and Human Services
1      95332422C0069         Millennium Challenge Corporation
2  1333ND23PNB640570                   Department of Commerce
3      140M0124F0048               Department of the Interior
4      191NLE23F7003                      Department of State

                                              vendor       value  \
0  VIRGINIA POLYTECHNIC INSTITUTE & STATE UNIVERSITY   333668.00
1                                         SB CONSEIL  1156093.25
2                                     DAVID SPARKMAN   414680.00
3                 INDUSTRIAL ECONOMICS, INCORPORATED   138499.90
4                       CREATIVE CORRECTIONS, L.L.C.   450457.56

                                         description fpds_status  \
0  MEASUREMENT OF GEOMECHANICAL PROPERTIES USING ...  TERMINATED
1  DIGITAL, DATA AND INNOVATION ECOSYSTEM ASSESSM...  TERMINATED
2  TECHNICAL CONSULTING SERVICES NIST MASS SPECTR...  TERMINATED
3                   SOUTH WIND DECISION FILE SUPPORT  TERMINATED
4                           PROGRAM ANALYST POSITION  TERMINATED

                                           fpds_link deleted_date   savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    5/19/2025       0.0
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    5/19/2025       0.0
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    5/19/2025  240810.0
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    5/16/2025       0.0
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    5/16/2025       0.0
Successfully created DataFrame DOGE.
             piid                                   agency  \
0  75D30123P15914  Department of Health and Human Services
1   1240BD22C0010                Department of Agriculture
2   36C26224P1551           Department of Veterans Affairs
3  75D30124P19626  Department of Health and Human Services
4   12FPC423P0065                Department of Agriculture

                                              vendor     value  \
0                  THERMO ELECTRON NORTH AMERICA LLC  131130.9
1  NATURAL RESOURCES, WASHINGTON STATE DEPARTMENT OF  120743.0
2                            WAHLBANGERS DRUM CIRCLE  120000.0
3                                       STRYDER CORP  100000.0
4                                  AGNET MEDIA, INC.   82500.0

                                         description fpds_status  \
0  TRACE 1300 GC, TRIPLUS RSH AUTOSAMPLER SERVICE...  TERMINATED
1  DATA SERVICES AND CLIMATE CHANGE VULNERABILITY...  TERMINATED
2                 DRUM CIRCLE MUSIC THERAPY SERVICES  TERMINATED
3             HANDSHAKE CAREER PLATFORM SUBSCRIPTION  TERMINATED
4  FLORIDA RADIO AND MEDIA OUTREACH SERVICES - NA...  TERMINATED

                                           fpds_link deleted_date  savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/9/2025  43710.3
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/9/2025      0.0
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/9/2025  98400.0
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/9/2025      0.0
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/9/2025  54000.0
Successfully created DataFrame DOGE.
                piid                  agency  \
0  1305M320PNFFR0395  Department of Commerce
1  1305M322PNFFS0478  Department of Commerce
2      1305M324P0459  Department of Commerce
3      1305M324P0460  Department of Commerce
4      1305M325P0041  Department of Commerce

                                              vendor      value  \
0  University Of California, Santa Barbara\r\n UE...    9930.82
1  University Of Alaska Fairbanks\r\n UEI: FDLEQS...  224930.00
2        Molecular Devices Llc\r\n UEI: L64RUJ7LC8T9   24340.00
3                Azenta Us Inc\r\n UEI: FW1MQC5H7K56   27535.50
4          Poll Everywhere Inc\r\n UEI: XKW1KJCGYKQ1   27500.00

                                         description         fpds_status  \
0  FACILITY FEES FOR USE OF FIELD VEHICLE, COMPUT...  EXERCISE AN OPTION
1         NON-PERSONAL SERVICES FOR ISOTOPE ANALYSIS  EXERCISE AN OPTION
2  THE SPECTRAMAX ID5 MULTIMODE (BRAND) PLATE REA...          BASE AWARD
3  messenger RNA (MRNA) EXTRACTION, LIBRARY PREPA...          BASE AWARD
4              POLL EVERYWHERE SOFTWARE-USER LICENSE          BASE AWARD

                                           fpds_link deleted_date  savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/6/2025      0.0
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/6/2025  59130.0
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/6/2025  16465.0
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/6/2025      0.0
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     5/6/2025  22000.0
Successfully created DataFrame DOGE.
                piid                           agency  \
0  70CMSD25FR0000005  Department of Homeland Security
1  70CMSD25FR0000004  Department of Homeland Security
2  70CMSD25FR0000006  Department of Homeland Security
3  70CMSD24FR0000131  Department of Homeland Security
4  70FA6023F00000020  Department of Homeland Security

                            vendor       value  \
0       GETTYSBURG ADDRESSES, INC.    85850.00
1       GETTYSBURG ADDRESSES, INC.    68425.00
2       GETTYSBURG ADDRESSES, INC.    71400.00
3                  GUIDEHOUSE INC.  1847840.00
4  GARUD TECHNOLOGY SERVICES, INC.  4232587.52

                                         description fpds_status  \
0                    LEADERSHIP DEVELOPMENT TRAINING  TERMINATED
1                    LEADERSHIP DEVELOPMENT TRAINING  TERMINATED
2                    LEADERSHIP DEVELOPMENT TRAINING  TERMINATED
3  Strategic communications support for Financial...  TERMINATED
4  ADMINISTRATIVE MANAGEMENT AND GENERAL MANAGEME...  TERMINATED

                                           fpds_link deleted_date     savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/30/2025        0.00
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/30/2025     9825.00
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/30/2025    26600.00
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/30/2025        0.00
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/30/2025  2594579.92
Successfully created DataFrame DOGE.
             piid                                   agency  \
0  75F40124F19009  Department of Health and Human Services
1  75F40124F19013  Department of Health and Human Services
2  75N93020F00001  Department of Health and Human Services
3  75N93024F00012  Department of Health and Human Services
4  75N93024F00057  Department of Health and Human Services

                                              vendor      value  \
0  SOLUTION PLANNING AND CONTRACT ENVIRONMENT INC...   47046.63
1                          VETS SYNERGETIC GROUP LLC  164261.60
2             ADVANCED BIOSCIENCE LABORATORIES, INC.   31202.00
3                          CAMRIS INTERNATIONAL INC.  584563.20
4                                GAP SOLUTIONS, INC.  583430.40

                                         description fpds_status  \
0  WHITE PLAINS RP FURNITURE-RELOCATION RECONFIGU...  TERMINATED
1  SCIENTIFIC SUPPORT FOR STEM CELL CHARACTERIZATION  TERMINATED
2                                ADMINISTRATIVE ASST  TERMINATED
3  NIAID PROFESSIONAL, SCIENTIFIC, AND TECHNICAL ...  TERMINATED
4  NIAID PROFESSIONAL, SCIENTIFIC, AND TECHNICAL ...  TERMINATED

                                           fpds_link deleted_date   savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/24/2025       0.0
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/24/2025       0.0
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/24/2025       0.0
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/24/2025  394310.4
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/24/2025  393542.4
Successfully created DataFrame DOGE.
            piid                                agency  \
0  140P2123P0036            Department of the Interior
1  140R3022C0006            Department of the Interior
2  9523ZY22F0086  Commodity Futures Trading Commission
3  9523ZY24F0028  Commodity Futures Trading Commission
4  12314424F0254             Department of Agriculture

                         vendor      value  \
0  FIRST AMERICAN TITLE COMPANY    19913.0
1            SWCA, INCORPORATED  2376427.0
2                 GARTNER, INC.    99054.0
3                 GARTNER, INC.   366590.0
4                 GARTNER, INC.   408917.0

                                         description  \
0  DIRECT TITLE INSURANCE CARRIERS- LANDS- SAFR 1...
1                  ENVIRONMENTAL CONSULTING SERVICES
2  LIBRARIES AND ARCHIVES GARTNER RISK MANAGEMENT...
3  WEB SEARCH PORTALS AND ALL OTHER INFORMATION S...
4  WEB SEARCH PORTALS AND ALL OTHER INFORMATION S...

                   fpds_status  \
0  OTHER ADMINISTRATIVE ACTION
1                   TERMINATED
2                   TERMINATED
3                   TERMINATED
4                   TERMINATED

                                           fpds_link deleted_date   savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/16/2025       0.0
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/16/2025  742335.0
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/15/2025       0.0
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/15/2025  300314.0
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    4/15/2025       0.0
Successfully created DataFrame DOGE.
                piid                agency                    vendor   value  \
0  89303024FMA000557  Department of Energy                 ITM4G LLC  4996.0
1  89303024FMA400923  Department of Energy      JB CONTRACTING, INC.  5600.0
2  89303024FMA400912  Department of Energy      JB CONTRACTING, INC.  5621.0
3  89303024FMA400808  Department of Energy      JB CONTRACTING, INC.  5968.0
4  89303024FMA400890  Department of Energy  HUGH AND ASSOCIATES INC.  6124.0

                                         description  \
0                         Multiple carpet labor jobs
1                       Perform Single paint project
2                       Perform Single paint project
3                       Perform Single paint project
4  Alteration project to install sound soak in co...

                                         fpds_status fpds_link deleted_date  \
0  Below Micro Purchase Level of $25k, Micro Purc...               4/9/2025
1  Below Micro Purchase Level of $25k, Micro Purc...               4/9/2025
2  Below Micro Purchase Level of $25k, Micro Purc...               4/9/2025
3  Below Micro Purchase Level of $25k, Micro Purc...               4/9/2025
4  Below Micro Purchase Level of $25k, Micro Purc...               4/9/2025

   savings
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
Successfully created DataFrame DOGE.
            piid                          agency  \
0    Unavailable                           USAID
1  19AQMM23F2560             Department of State
2  24322624F0175  Office of Personnel Management
3  24322624F0094  Office of Personnel Management
4  24322624F0228  Office of Personnel Management

                               vendor       value  \
0                         Unavailable    19040.00
1         ACADEMI TRAINING CENTER LLC  3749665.12
2  INSIGHT MANAGEMENT CONSULTING, LLC    11879.00
3  INSIGHT MANAGEMENT CONSULTING, LLC     6052.00
4  INSIGHT MANAGEMENT CONSULTING, LLC     4989.00

                                         description  \
0                      Unavailable for legal reasons
1  OTHER MANAGEMENT CONSULTING SERVICES UNRESTRIC...
2     Crucial conversations virtual participant kits
3                      Crucial Conversations Packets
4  Crucial Conversations packets for VHA training...

                                         fpds_status  \
0                                        Unavailable
1                                         TERMINATED
2                                            Expired
3  Below Micro Purchase Level of $25k, Micro Purc...
4  Below Micro Purchase Level of $25k, Micro Purc...

                                           fpds_link deleted_date     savings
0                                   https://fpds.gov    3/31/2025        0.00
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/28/2025  2283124.85
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/28/2025        0.00
3                                                       3/28/2025        0.00
4                                                       3/28/2025        0.00
Successfully created DataFrame DOGE.
             piid                         agency                 vendor  \
0  86615124F00008  Housing and Urban Development             KPMG LLP-3
1   47QFDA25K0007  Housing and Urban Development
2  86614324P00019  Housing and Urban Development  ENGINEERED FLOORS LLC
3  86614324F00044  Housing and Urban Development  GRAEBEL COMPANIES INC
4  86614124P00005  Housing and Urban Development        APPEXTREMES LLC

        value                                        description  \
0  1311212.79  Support to develop a Housing Counseling Impact...
1  4201201.00
2     9490.67                            Executive Suites carpet
3   585400.00  HUD Regional and Field Offices Private Branch ...
4    14431.20  COTS software - Conga Composer – Business Edit...

         fpds_status                                          fpds_link  \
0         TERMINATED  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...
1  NOT FOUND IN FPDS
2         TERMINATED  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...
3         TERMINATED  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...
4         TERMINATED  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...

  deleted_date     savings
0    3/20/2025   605499.41
1    3/20/2025  4201201.00
2    3/20/2025        0.00
3    3/20/2025        0.00
4    3/20/2025        0.00
Successfully created DataFrame DOGE.
                piid                                   agency  \
0     75N94020F00001  Department of Health and Human Services
1     75N94023F00001  Department of Health and Human Services
2  89243124FSC000020                     Department of Energy
3  89303024FIM000142                     Department of Energy
4      91990022F0322                  Department of Education

                                vendor        value  \
0  The Trustees of Columbia University     97659.00
1  The Trustees of Columbia University     87270.00
2       ACCENTURE FEDERAL SERVICES LLC   1584979.95
3       ACCENTURE FEDERAL SERVICES LLC  10919584.27
4                      GUIDEHOUSE INC.   5127798.60

                                         description  \
0  TO ASSIST IN THE DEVELOPMENT OF NEW CONTRACEPT...
1  OVAPRENE PHASE 1 - PROTOCOL FINALIZATION, PROC...
2  Cyber Security contract for Small Business Inn...
3  CHIEF INFORMATION OFFICER BUSINESS OPERATIONS ...
4  THIS ACTION PROVIDES THE DEPARTMENT WITH SUPPO...

                                    fpds_status  \
0                                    TERMINATED
1                                    TERMINATED
2                   OTHER ADMINISTRATIVE ACTION
3  SUPPLEMENTAL AGREEMENT FOR WORK WITHIN SCOPE
4                   OTHER ADMINISTRATIVE ACTION

                                           fpds_link deleted_date     savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/10/2025    29343.00
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/10/2025        0.00
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/10/2025  1066579.65
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/10/2025  7752407.61
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...    3/10/2025  3333064.00
Successfully created DataFrame DOGE.
          piid agency       vendor      value                    description  \
0  Unavailable  USAID  Unavailable  1350604.0  Unavailable for legal reasons
1  Unavailable  USAID  Unavailable  1081801.0  Unavailable for legal reasons
2  Unavailable  USAID  Unavailable  1122473.0  Unavailable for legal reasons
3  Unavailable  USAID  Unavailable  1180672.0  Unavailable for legal reasons
4  Unavailable  USAID  Unavailable  1424238.0  Unavailable for legal reasons

   fpds_status         fpds_link deleted_date    savings
0  Unavailable  https://fpds.gov    3/10/2025  1094929.0
1  Unavailable  https://fpds.gov    3/10/2025   887721.0
2  Unavailable  https://fpds.gov    3/10/2025   921133.0
3  Unavailable  https://fpds.gov    3/10/2025   967501.0
4  Unavailable  https://fpds.gov    3/10/2025  1154679.0
Successfully created DataFrame DOGE.
                piid                                   agency  \
0     75D30124C19204  Department of Health and Human Services
1     75D30120C08280  Department of Health and Human Services
2     75D30120C09982  Department of Health and Human Services
3  70RSAT20P00000022          Department of Homeland Security
4  15JA0520P00000086                    Department of Justice

                                          vendor        value  \
0      CHEROKEE NATION INTEGRATED HEALTH, L.L.C.   3829663.92
1                          SYNERGY AMERICA, INC.   3831223.77
2  CHEROKEE NATION OPERATIONAL SOLUTIONS, L.L.C.  12965173.62
3                             CQ-ROLL CALL, INC.    271347.00
4                        SACHS MEDIA GROUP, INC.    429000.00

                        description fpds_status  \
0            OSER TECHNICAL SUPPORT  TERMINATED
1  SYNERGY 8(A) SERVICE REQUIREMENT  TERMINATED
2            DEHSP SUPPORT SERVICES  TERMINATED
3       TERMINATION FOR CONVENIENCE  TERMINATED
4           PUBLIC AFFAIRS SERVICES     Expired

                                           fpds_link deleted_date     savings
0  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     3/4/2025  2950996.48
1  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     3/4/2025   131733.69
2  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     3/4/2025  1276729.71
3  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     3/4/2025        0.00
4  https://www.fpds.gov/ezsearch/jsp/viewLinkCont...     3/4/2025   358114.50
Successfully created DataFrame DOGE.
          piid agency       vendor      value                    description  \

In [ ]:
len(dfs)

23

In [ ]:
dfs[5]

,piid,agency,vendor,value,description,fpds_status,fpds_link,deleted_date,savings
0,75F40124F19009,Department of Health and Human Services,SOLUTION PLANNING AND CONTRACT ENVIRONMENT INC...,47046.63,WHITE PLAINS RP FURNITURE-RELOCATION RECONFIGU...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/24/2025,0.00
1,75F40124F19013,Department of Health and Human Services,VETS SYNERGETIC GROUP LLC,164261.60,SCIENTIFIC SUPPORT FOR STEM CELL CHARACTERIZATION,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/24/2025,0.00
2,75N93020F00001,Department of Health and Human Services,"ADVANCED BIOSCIENCE LABORATORIES, INC.",31202.00,ADMINISTRATIVE ASST,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/24/2025,0.00
3,75N93024F00012,Department of Health and Human Services,CAMRIS INTERNATIONAL INC.,584563.20,"NIAID PROFESSIONAL, SCIENTIFIC, AND TECHNICAL ...",TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/24/2025,394310.40
4,75N93024F00057,Department of Health and Human Services,"GAP SOLUTIONS, INC.",583430.40,"NIAID PROFESSIONAL, SCIENTIFIC, AND TECHNICAL ...",TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/24/2025,393542.40
...,...,...,...,...,...,...,...,...,...
495,Unavailable,USAID,Unavailable,476636.40,Unavailable for legal reasons,Unavailable,https://fpds.gov,4/16/2025,0.00
496,Unavailable,USAID,Unavailable,672508.00,Unavailable for legal reasons,Unavailable,https://fpds.gov,4/16/2025,446222.00
497,75N93023C00012,Department of Health and Human Services,PLURI BIOTECH LTD,4175467.00,DEVELOPMENT OF PLX-R18 CELL THERAPY AS A COUNT...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/16/2025,1313852.00
498,75D30122C14874,Department of Health and Human Services,"KATMAI RESOURCE MANAGEMENT, LLC",24970188.18,OSH PROFESSIONAL/TECHNICAL SUPPORT SERVICES (P...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/16/2025,10009256.46
499,140A1624P0057,Department of the Interior,"FORRESTER RESEARCH, INC.",182715.67,CUSTOMER EXPERIENCE / USER EXPERIENCE TRAINING...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,4/16/2025,0.00

In [ ]:
pd.concat(dfs, ignore_index=True)

,piid,agency,vendor,value,description,fpds_status,fpds_link,deleted_date,savings
0,2032H824F00058,Department of Treasury,DELOITTE CONSULTING LLP,7.259739e+06,Comprehensive Training Strategy aimed at enhan...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,6/3/2025,4.354402e+06
1,20341522F00039,Department of Treasury,"FI CONSULTING, INC.",2.992678e+06,Independent Verification and Validation,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,6/3/2025,0.000000e+00
2,75D30124F19709,Department of Health and Human Services,FAMILY HEALTH INTERNATIONAL,1.428250e+08,HUMAN IMMUNODEFICIENCY VIRUS COMMUNICATIONS PR...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,6/3/2025,1.245576e+08
3,Unavailable,USAID,Unavailable,9.499996e+07,Unavailable for legal reasons,Unavailable,https://fpds.gov,6/3/2025,6.524996e+07
4,95170024C0273,United States Agency for Global Media,MISCELLANEOUS FOREIGN AWARDEES,1.767699e+07,MEDIUM WAVE RADIO BROADCASTING TRANSMISSION SE...,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,6/3/2025,1.608278e+07
...,...,...,...,...,...,...,...,...,...
11037,2032H321A00002,Department of Treasury,Hispanic Assoc. of Colleges and Universities,6.500000e+06,DEIA Training,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,1/22/2025,6.500000e+06
11038,75N96024F00045,Department of Health and Human Services,Powertrain Inc.,2.093948e+05,DEIA Training,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,1/22/2025,0.000000e+00
11039,2032H824F00064,Department of Treasury,"STEEL POINT SOLUTIONS, LLC",5.265565e+06,DEIA Training,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,1/22/2025,2.323823e+06
11040,12314423C0053,Department of Agriculture,"TIMOTHY J. LONDAGIN, LLC",2.035756e+06,DEIA Training,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,1/22/2025,9.202590e+05
11041,89243423FEE000303,Department of Energy,THE BUILDING PEOPLE LLC,3.042432e+05,DEIA Training,TERMINATED,https://www.fpds.gov/ezsearch/jsp/viewLinkCont...,1/21/2025,9.884131e+04

In [ ]:
contracts = pd.concat(dfs, ignore_index=True)

In [ ]:
# save concat to google drive as contracts

from google.colab import drive
drive.mount('/content/drive')
contracts.to_csv('/content/drive/My Drive/DOGE/contracts.csv', index=False)

print("DataFrame 'contracts' saved to Google Drive as contracts.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
DataFrame 'full_contracts' saved to Google Drive as contracts.csv

In [ ]:
url = 'https://api.doge.gov/savings/contracts'
headers = {'accept': 'application/json'}

response = requests.get(url, headers=headers)

if response.status_code == 200:
  data = response.json()

  if data and 'result' in data:
    DOGE = pd.DataFrame(data['result'])
    print("Successfully created DataFrame DOGE.")
    print(DOGE.head())
  else:
    print("API response does not contain 'result' key.")
else:
  print(f"Error fetching data. Status code: {response.status_code}")
  print("Response body:", response.text)

Successfully created DataFrame DOGE.
                                           contracts
0  {'piid': '2032H824F00058', 'agency': 'Departme...
1  {'piid': '20341522F00039', 'agency': 'Departme...
2  {'piid': '75D30124F19709', 'agency': 'Departme...
3  {'piid': 'Unavailable', 'agency': 'USAID', 've...
4  {'piid': '95170024C0273', 'agency': 'United St...

In [ ]:
# prompt: print DOGE dataframe info

DOGE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   contracts  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes